### ISSUE TITLE
Txs won't propagate, if same account sends on two different nodes

### ISSUE THREAD

**Issue by pdobacz** [cosmos/ethermint-archive#10]
I am experiencing following strange behaviour:

Having N (validating) nodes and unlocking (`personal.unlockAccount`) accounts on them everything seems to be working fine (I am able to send txs and they propagate)

This is true as long as I use `getTransactionCount` for nonce every time, but breaks as soon as I attempt to set a nonce higher than needed. Breaks = transactions do not propagate, they seem to go through `geth` fine, but never make it to the block. And after it breaks, it won't work even for the exact `getTransactionCount` nonce anymore.

Other kind of strange thing I've noticed is that if I send transactions from acount `A` using node 1, and then attempt to send a transaction from A using node 2, it breaks the same way. A transactions only propagate when sent using node 1 from then on. As if the node 1 kept some other "nonce" that is invisible to node 2.

Sorry for the vague description, but that's all I have for now. Will continue to investigate, but does that ring any bell? (edited)

ebuchman [5:32 PM]  

>Sounds like some kind of mempool bug. We'll have to investigate. Tha ks fir the report!

**Comment by pdobacz** [comment]
Steps to reproduce:

1) run 2 ethermint peer nodes
2) `personal.importRawKey()` + `personal.unlockAccount()` on 2 of them, same key
3) send as many txs using node 1 as you like - they propagate
4) txs won't propagate if sent using the key from node 2

What matters is which node sends the first transaction for the key.

^ this you will get if you specify nonce explicitly in `sendTransaction` as `getTransactionCount` for the given account. If you leave nonce up to the client, you get `Nonce too low`

Ethermint commit 211283c2bcad20904f1da0941da5bb04f272794f, run using Docker

**Comment by pdobacz** [comment]
Update:

I've managed to establish that both behaviors, i.e. with or without using the `getTransactionCount`to provide the exact Nonce, are caused by the same thing.

The node `A` that is **receiving** a transaction sent from that account `X`, sets the nonce for `X` properly in `managed_state.go:99` - `pool.pendingState.SetNonce` in `promoteTx`. Then the reference to the object holding that infomation is lost.

When that node `A` tries to **send** from `X`, the `pool.pendingState.GetNonce(addr)` returns 0.

**Comment by ebuchman** [comment]
Thanks for the great investigative work. We really need to stop using the geth transaction pool and implement something much simpler ourselves. The only drawback is we have to replicate the logic for a valid mempool transaction since it's not exposed in go-ethereum/core. This shouldn't be too hard to do - but we could really use some help with getting these kinks ironed out and adding proper tests while we're busy firing away on tendermint and its more closely related repos.

**Comment by pdobacz** [comment]
This seems to be fixed in `major-update`, as of 5f989e08ec52155952956ebe3fb62fae94cbdf47. So no need for #12 quickfix anymore.

Will close as soon as `major-update` gets mergged

**Comment by ebuchman** [comment]
Awesome! major-update merged. Closing. Thanks!
