### ISSUE TITLE
Implement a permissioning framework for ethermint as a smart contract

### ISSUE THREAD

**Issue by 4gn3s** [cosmos/ethermint-archive#11]
This is a feature request. I would like to be able to define a few different levels of access to ethermint network using smart contracts:
1. network participation; nodes in this group can access full network state, and receive new transactions and blocks
2. validators; nodes in this group can validate new blocks
3. transaction creation; nodes in this group are allowed to create new transactions in the system

Smart contracts are registars, and it is these smart contracts' logic that exclusively modifies the whitelists.
The framework allows to bootstrap a network (probably as a genesis file) and then add and remove new nodes to groups by already approved nodes.

**Comment by adrianbrink** [comment]
Ethermint is designed to run a copy that is as close to go-ethereum as possible on top of tendermint and hence I'm closing this.
