### ISSUE TITLE
Incorporate git-hash in the version.

### ISSUE THREAD

**Issue by jaekwon** [cosmos/ethermint-archive#15]
Currently: `Ethermint/v0.1.0-unstable/linux/go1.6.2`

Geth does: `Geth/v1.5.6-unstable-e0ee0cc6/linux/go1.7.4`

We could do something similar for Tendermint in general

**Comment by illya13** [comment]
I think `go-ethereum` version used also should be visible as well

**Comment by ramilexe** [comment]
@illya13 
>I think go-ethereum version used also should be visible as well

version of our `go-ethereum` fork?

**Comment by adrianbrink** [comment]
I agree with @illya13. It will make debugging in the future much easier.

**Comment by ramilexe** [comment]
We can close this issue. It already in master https://github.com/tendermint/ethermint/blob/master/version/version.go#L31
