### ISSUE TITLE
Sending IBC packets to/from ethermint

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#158]
Implementing IBC for ethermint will enable the connection to the COSMOS hub. 

There are two approaches:
1. Reimplement ethermint as a cosmos-sdk module.

2. Pull the IBC parts from the cosmos-sdk and implement IBC into ethermint.

I heavily favour approach 2, since it will most likely be much less work and should happen much quicker. Furthermore, I think there is an advantage to showing how other blockchains can use only certain parts of the cosmos-sdk without having to rewrite their entire software to work with our datastructures.

**Comment by ebuchman** [comment]
Yes we should go with approach 2. Basic idea is to implement a native contract with its own IAVL tree to handle this. I can sketch something up this week.

**Comment by adrianbrink** [comment]
Sweet looking forward to it.

**Comment by rigelrozanski** [comment]
Can this be resolved by implementing ethermint as a cosmos-sdk module? Then can take advantage of the IBC module which @ethanfrey has built?

**Comment by adrianbrink** [comment]
Jae, Bucky and me had a long discussion on this. For now we will pull in the cosmos-sdk into ethermint instead of re-writing ethermint around the cosmos-sdk. 

So, this will take advantage of the IBC module by importing it into ethermint.

**Comment by rigelrozanski** [comment]
cool

**Comment by freemanjackal** [comment]
is there something done about this, that i could check how to implement IBC in my project?  where can i find it?

**Comment by zramsay** [comment]
looks like consensus was acheived. closing as resolved
