### ISSUE TITLE
smoke test the minikube documentation

### ISSUE THREAD

**Issue by mohamedGr** [cosmos/ethermint-archive#171]
Hi,

I tried to create a cluster of ethermint nodes using the steps from the Multi-Node Deployments section using the kubernetes start.sh script but I the pod tm-0 gets stuck in the **Init:CrashLoopBackOff** phase and I get the following error from the dashboard:

SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "tmdir-tm-0", which is unexpected.
Error syncing pod, skipping: failed to "InitContainer" for "eth-init" with RunInitContainerError: "init container \"eth-init\" exited with 1"
Back-off restarting failed container****

Can anyone please help me with this issue?

Thank you!

**Comment by adrianbrink** [comment]
How much time do you leave between calling `./scripts/start.sh 4 4 4` and checking? Initially, that is an expected error message.

Then you should wait around 5 minutes and then check if the error disappears. Kubernetes needs quite a lot of time for the first start-up.

**Comment by mohamedGr** [comment]
Hi Adrian,
Thanks for your reply, I always keep it running for hours actually and every time it gets stuck **Init:CrashLoopBackOff** phase. This is a screenshot from the minikube dashboard showing that this was running for more than 25min but still the same issue.

![image](https://user-images.githubusercontent.com/5721014/27749192-8a65bfaa-5da0-11e7-998c-ab97ec110643.png)

When I check with $kubectl get pods,  it gives me;

![image](https://user-images.githubusercontent.com/5721014/27749222-acbcb8f6-5da0-11e7-91c5-55169e13fb9c.png)


And this changed from **Init:CrashLoopBackOFF** to **Init:Error** after 11 **RESTARTS**

**Comment by adrianbrink** [comment]
Can you run the minikube examples?

**Comment by adrianbrink** [comment]
And what system are you running on?

**Comment by mohamedGr** [comment]
I am using Ubuntu 16.04. Is it possible to run multiple ethermint nodes using separate remote VMs without using kubernetes?

**Comment by adrianbrink** [comment]
Yes, you can run them on separate VMs. When starting the nodes you just have to provide the correct IP addresses in the `--p2p.seeds` flag.

**Comment by romeo4934** [comment]
actually we are working a version with docker-compose and docker stack deploy. It is the same philosophy than kubernetes but without kubernetes ;) It is a work in progress but you can check here
https://github.com/multiverseHQ/deployment/tree/master/docker_files

**Comment by mohamedGr** [comment]
Do I need to specify an abci for tendermint if I am running ethermint on top of it? Because when I run the following command:
`tendermint --home ~/.ethermint/tendermint node
`
This is what I get:

`E[07-10|15:35:55.813] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query`

Thanks!

**Comment by adrianbrink** [comment]
You need to also run a tendermint core instance.

https://github.com/tendermint/ethermint#running

**Comment by mohamedGr** [comment]
I followed those same steps actually. I ran these commands:
```

tendermint init --home ~/.ethermint/tendermint

cd $GOPATH/src/github.com/tendermint/ethermint

ethermint --datadir ~/.ethermint init setup/genesis.json

cp -r setup/keystore ~/.ethermint
```
I included 4 validators in `~/.ethermint/tendermint/genesis.json` 
then ran this command from the first validator and specified the 3 other seeds as below:

`tendermint --home ~/.ethermint/tendermint node --p2p.seeds "10.10.22.1:46656,10.10.23.1:46656,10.10.24.2:46656"`

But I still receive the same error.

Adding `--proxy_app=dummy` seems to fix the issue but I don't know whether that's the right way to do it.
Thanks

**Comment by adrianbrink** [comment]
`--proxy_app=dummy` means that it is using an example app instead of `ethermint`.

you also need to run `ethermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin`

You need to run `tendermint` and `ethermint` in two separate terminal windows at the same time.

**Comment by mohamedGr** [comment]
That's what I did actually but it turns out this was due to a synchronization problem between the VMs that I am using.
Thanks a lot for your help!

**Comment by SurabhiBorgikar** [comment]
Hi
I see this issue while setting up  Ethermint on Kubernetes cluster on GCE. Using the `./start.sh 4 4 4` command. Kubernetes cluster with 4 nodes. tm-0 pod status: `  Init:CrashLoopBackOff  `

In the tm-0 logs I see :
`Error from server (BadRequest): a container name must be specified for pod tm-0, choose one of: [tm app pub-key] or one of the init containers: [tm-gen-validator eth-init]` 

And in `kubectl logs tm-0 eth-init` : 

`+ cp -rv '/ethinit/*' /ethermint/`
`cp: can't stat '/ethinit/*': No such file or directory`

Need help with this issue.

Thanks!

**Comment by zramsay** [comment]
new docs will be in https://github.com/cosmos/ethermint
