### ISSUE TITLE
Write a guide that explains and simplifies connecting to our testnets

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#179]
Currently connecting to the testnets requires you to follow a specific blog posts.

There needs to be documentation (see #225 for more information on docs) that explains how to connect to the testnets.

Furthermore, it should be very quick and simple to connect to the testnets after having installed ethermint. There should be cli commands and flags that automatically connect you to a certain public ethermint network.

- [ ] Test it with 2 users that have never used ethermint or venus and just watch them follow the guide. Then update accordingly

**Comment by adrianbrink** [comment]
@odeke-em What do you think about extending the CLI to actually cover the use case of connecting to one of our testnets?

**Comment by odeke-em** [comment]
SGTM! I can take a look at this when I get up, thanks.

**Comment by zramsay** [comment]
just a thought: `ethermint init` could have a flag `--testnets` that generates the required files. `tendermint init` could have the same feature, so we can skip the `git clone the-testnets-repo` and `cp` sequence. would be an extension of #245

**Comment by adrianbrink** [comment]
The idea is that we hardcode the genesis files for tendermint validators and ethermint into the binary. When you then specify `ethermint start --testnet --home ...` ethermint initialises with the testnet genesis file and overrides the genesis file for tendermint.

Let's also consider that we start `tendermint` automatically in the background by using `https://golang.org/pkg/os/exec/` to issue `tendermint init --home` and `tendermint node`.

**Comment by odeke-em** [comment]
@adrianbrink the tricky thing that am thinking about doing https://github.com/tendermint/ethermint/issues/179#issuecomment-323279155 is that what if the user doesn't want to reinit tendermint?
A solution to that is to add an opt-out flag say `--no-tendermint` which will be documented to opt out of invoking `tendermint init` when `ethermint init` is invoked and `tendermint node` when `ethermint` is invoked. I think the new cosmos-ui by @mappum et all currently invokes both `baseserver` and `tendermint`

**Comment by adrianbrink** [comment]
The flag should be `--without-tendermint` to be consistent with the rest of the apps.

**Comment by zramsay** [comment]
the original issue is merged
