### ISSUE TITLE
Stop go-ethereum from starting the networking layer

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#192]
Currently, when ethermint starts the go-ethereum stack, go-ethereum also starts its own networking stack. As such it allocates resources and ports (30303) unnecessarily. 

Furthermore the problem becomes that we currently cannot run go-ethereum and ethermint next to each other without having to change the ports on go-ethereum. This will become a problem for the future peg-zone.

**Comment by ramilexe** [comment]
This port binded by go-ethereum p2p: https://github.com/tendermint/go-ethereum/blob/master/node/defaults.go#L44
But where it binded by ethermint?

**Comment by ramilexe** [comment]
PR: https://github.com/tendermint/ethermint/pull/206
