### ISSUE TITLE
Show api documentation through godoc

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#195]
- [x] add explanation on how to access and run godoc for ethermint to README
- [x] mark all exposed APIs as unstable
- [x] make sure that all exposed functions, methods and structures are properly documented
- [ ] write a note into the README about how unstable APIs can change at any moment and shouldn't be relied on, it will still be mentioned in the change log
- [ ] add running it to the Makefile

Once this is done, slowly start marking APIs as stable and then those APIs follow semver

**Comment by odeke-em** [comment]
How's it going @adrianbrink?
How would you like us to proceed with this work? Is it urgent for the next release?

**Comment by adrianbrink** [comment]
This is not urgent. However the only thing that is left for this one is to make sure that the README properly explains how to run godoc and how to access it. Besides that it might be nice to properly format some of the doc comments in the code.

**Comment by zramsay** [comment]
did #236 handle this issue? also https://godoc.org/github.com/tendermint/ethermint does the trick, no?
