### ISSUE TITLE
Make linting checks part of the development process

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#196]
We should strive to only have very clean code for ethermint.

We currently have two separate linters `gometalinter` and `megacheck`.

As such this issue is three fold:
1. Add an explanation of how to install all our linters.
2. Update the Makefile so that the linters get run on every test and build run.
3. Update the CI build steps to fail on linting errors.

**Comment by rigelrozanski** [comment]
This should not be specific to ethermint, needs to be streamlined with tendermint coding standards/practices... here https://github.com/tendermint/coding/blob/master/go/coding_standard.md#linters
But also https://github.com/tendermint/coding/

Maybe sync up with @zramsay on this end for the documentation, I know zach has been modifying and organizing the coding repo

**Comment by zramsay** [comment]
I'm assigning myself to tackle the standard (rather then implementation). On points 1 & 2 i think we should just list those standards/explanations/Makefile examples in the coding repo - otherwise every new "major" repo is going to go through the same issues repeatedly.

**Comment by adrianbrink** [comment]
Please check https://github.com/tendermint/ethermint/blob/develop/Makefile#L69 to see which linters are running. I've mostly fixed up ethermint that those pass.
