### ISSUE TITLE
Failed to set version on github.com/ethereum/go-ethereum to c71a185de835d24ffaea21bc045649eed8e0ce20

### ISSUE THREAD

**Issue by NathanLewis** [cosmos/ethermint-archive#198]
Commit c71a185de835d24ffaea21bc045649eed8e0ce20 doesn't seem to exist in the repository.
I cloned the repo and checked the logs after the glide install failed. I tried changing the commit hash to the 1.6.6 stable version but that doesn't work either. How do we get the install to work?

**Comment by adrianbrink** [comment]
@NathanLewis I can reproduce it and will fix it this weekend. For now make sure that you are on the `develop` branch.

**Comment by ramilexe** [comment]
Investigated this issue.
Glide output with `--debug` flag:

`Output was: fatal: reference is not a tree: c71a185de835d24ffaea21bc045649eed8e0ce20`

@adrianbrink did you force pushed that commit?

**Comment by adrianbrink** [comment]
This should be fixed in the newest release and branches of master and develop
