### ISSUE TITLE
Remove vendor directory

### ISSUE THREAD

**Issue by jaekwon** [cosmos/ethermint-archive#2]
Including the vendor dir will make debugging impossible w/ potential dependency issues.

Lets remove vendor and include instructions for glide.

**Comment by ebuchman** [comment]
Yeh, once we're shipping binaries

**Comment by kobigurk** [comment]
How about - let's keep vendor in, as whoever wants to `go get` it will have the opportunity to do it seamlessly, but developers will have to manually erase the vendor and do `glide install`?
That way, we maintain both the glide config and the vendor dir so it works for both ways.

**Comment by illya13** [comment]
👍 for keep `vendor` and `glide` provide instructions
