### ISSUE TITLE
Explain what is ethermint and how it can be used

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#208]
This issue involves updating the documentation (#225) to explain what ethermint is and what it can be used for. 

It means following:
- you can start private chain
- not connected to public Ethereum network, but see `Cosmos`
- on API / Smart Contracts level your network is compatible with Ethereum libraries, i.e. you can deploy smart contract written for public Ethereum
- your client apps are also compatible because of `web3` compatibility
- you can use the same tools for development like `truffle` and so on

**Comment by zramsay** [comment]
mostly covered in the docs. if they have specific point that need improvement then let's make issues for those

**Comment by b00f** [comment]
I have published this repository to run private network with ethermint and tendermint. You can check it here:
https://github.com/b00f/ethermint-private-network

**Comment by zramsay** [comment]
awesome @b00f
