### ISSUE TITLE
ethermint: command not found

### ISSUE THREAD

**Issue by rts-2** [cosmos/ethermint-archive#212]
I'm following the steps to install ethermint on top of tendermint that are listed on the README on this github page: https://github.com/tendermint/ethermint, but at the step ethermint --datadir ~/.ethermint init setup/genesis.json, then I get the following error: ethermint: command not found  And yes, I installed tendermint previous to my attempted installation of ethermint.

**Comment by adrianbrink** [comment]
How did you install `ethermint`?

You can either download the [binaries](https://github.com/tendermint/ethermint/releases/tag/v0.4.0) from the release page or install from [source](https://github.com/tendermint/ethermint/tree/v0.4.0#source).

Once you have followed either of those steps, please run `ethermint version` to test the correct installation of `ethermint`.

**Comment by rts-2** [comment]
I installed from source. I cannot run `ethermint version` because that returns the same error: `ethermint: command not found.`

**Comment by ebuchman** [comment]
can you give us the output of:

```
go version
echo $GOPATH
```

Most likely, the location of the binary is not on your `$PATH`. If `$GOPATH` is set, you can add `export PATH=$GOPATH/bin:$PATH` to add it. If it's not set, the default in newer versions of go is `$HOME/go`. 

Regardless, you should be able to run ethermint by providing the explicit path: `$GOPATH/bin/ethermint version`, or if the GOPATH is not set, `~/go/bin/ethermint version`

**Comment by rts-2** [comment]
Output from `go version`
`go version go1.6.2 linux/amd64`
Output from `echo $GOPATH`
`/home/robert/.go`

What does this mean?

**Comment by ebuchman** [comment]
That's fine. So you can find ethermint under `$GOPATH/bin/ethermint`. Ie. run `$GOPATH/bin/ethermint version`.

To avoid having to type all that, add `$GOPATH/bin` to your $PATH.

**Comment by rts-2** [comment]
How do I add $GOPATH/bin to my $PATH?

**Comment by ebuchman** [comment]
add the following line to your `~/.bashrc`. then open a new terminal window:

```
PATH=$GOPATH/bin:$PATH
```

**Comment by rts-2** [comment]
Hmm, I did that, and `ethermint version` still gives me an error

**Comment by adrianbrink** [comment]
Can you run `echo $PATH`, `echo $GOPATH` and `echo $GOROOT`.

Also, please describe the steps that you took to install from source. 

Lastly, we don't support `go 1.6`. Could you install at least `go 1.8`. I would recommend [gvm](https://github.com/moovweb/gvm).

**Comment by rts-2** [comment]
`echo $PATH` result:
`/home/robert/.go/bin:/home/robert/.nvm/versions/node/v6.11.1/bin:/home/robert/bin:/home/robert/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
`echo $GOPATH` result:
`/home/robert/.go/`
`echo $GOROOT` does not do anything for me.

**Comment by adrianbrink** [comment]
Could you walk through these steps to install from source:

`go get github.com/tendermint/ethermint`

`cd $GOPATH/src/github.com/tendermint/ethermint`

`make install`

Please report the output of each of these commands.

**Comment by ebuchman** [comment]
Could you also give us the output of `ls $GOPATH/bin`?

**Comment by rts-2** [comment]
`go get github.com/tendermint/ethermint`:
`can't load package: package github.com/tendermint/ethermint: no buildable Go source files in /home/robert/.go/src/github.com/tendermint/ethermint`
`cd $GOPATH/src/github.com/tendermint/ethermint`:
prompt changes to `~/.go/src/github.com/tendermint/ethermint$`
`make install`:

`go get github.com/karalabe/xgo github.com/Masterminds/glide honnef.co/go/tools/cmd/megacheck github.com/alecthomas/gometalinter
--> Running glide install
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/aristanetworks/goarista 8ab803d6502ea1e05a8c9b73193b405291efb7ce!
[INFO]	--> Found desired version locally github.com/btcsuite/btcd 47885ab8702485be6b6f87a03d4f3be0bc5c982c!
[INFO]	--> Found desired version locally github.com/edsrzf/mmap-go 0bce6a6887123b67a60366d2c9fe2dfb74289d2e!
[INFO]	--> Found desired version locally github.com/ethereum/go-ethereum 7db2143396f73f418b50dc5571fec2c62c78b7e4!
[INFO]	--> Found desired version locally github.com/fatih/color 62e9147c64a1ed519147b62a56a14e83e2be02c1!
[INFO]	--> Found desired version locally github.com/go-kit/kit 69950137349e3e6781c1a54e4f7fd3803bd36765!
[INFO]	--> Found desired version locally github.com/go-logfmt/logfmt 390ab7935ee28ec6b286364bba9b4dd6410cb3d5!
[INFO]	--> Found desired version locally github.com/go-stack/stack 54be5f394ed2c3e19dac9134a40a95ba5a017f7b!
[INFO]	--> Found desired version locally github.com/golang/protobuf 0a4f71a498b7c4812f64969510bcb4eca251e33a!
[INFO]	--> Found desired version locally github.com/golang/snappy 553a641470496b2327abcac10b36396bd98e45c9!
[INFO]	--> Found desired version locally github.com/gorilla/websocket a69d9f6de432e2c6b296a947d8a5ee88f68522cf!
[INFO]	--> Found desired version locally github.com/hashicorp/golang-lru 0a025b7e63adc15a622f29b0b2c4c3848243bbf6!
[INFO]	--> Found desired version locally github.com/huin/goupnp 73053506a919bb1af6beb97feb0d53a1eb814eb1!
[INFO]	--> Found desired version locally github.com/jackpal/go-nat-pmp 28a68d0c24adce1da43f8df6a57340909ecd7fdd!
[INFO]	--> Found desired version locally github.com/karalabe/hid 875879887cf0560a993b57e04615944e1dd02a73!
[INFO]	--> Found desired version locally github.com/kr/logfmt b84e30acd515aadc4b783ad4ff83aff3299bdfe0!
[INFO]	--> Found desired version locally github.com/mattn/go-colorable 941b50ebc6efddf4c41c8e4537a5f68a4e686b24!
[INFO]	--> Found desired version locally github.com/mattn/go-isatty fc9e8d8ef48496124e79ae0df75490096eccf6fe!
[INFO]	--> Found desired version locally github.com/pborman/uuid e790cca94e6cc75c7064b1332e63811d4aae1a53!
[INFO]	--> Found desired version locally github.com/peterh/liner 88609521dc4b6c858fd4c98b628147da928ce4ac!
[INFO]	--> Found desired version locally github.com/pkg/errors c605e284fe17294bda444b34710735b29d1a9d90!
[INFO]	--> Found desired version locally github.com/rcrowley/go-metrics 1f30fe9094a513ce4c700b9a54458bbb0c96996c!
[INFO]	--> Found desired version locally github.com/rjeczalik/notify 88a54d914928e1faebb1c2195605dc87bd98dc27!
[INFO]	--> Found desired version locally github.com/robertkrimen/otto 49fee9c1c0db1c366003ede4cc665f9924a97521!
[INFO]	--> Found desired version locally github.com/rs/cors 8dd4211afb5d08dbb39a533b9bb9e4b486351df6!
[INFO]	--> Found desired version locally github.com/spf13/pflag e57e3eeb33f795204c1ca35f56c44f83227c6e66!
[INFO]	--> Found desired version locally github.com/syndtr/goleveldb 8c81ea47d4c41a385645e133e15510fc6a2a74b4!
[INFO]	--> Found desired version locally github.com/tendermint/abci 864d1f80b36b440bde030a5c18d8ac3aa8c2949d!
[INFO]	--> Found desired version locally github.com/tendermint/ed25519 1f52c6f8b8a5c7908aff4497c186af344b428925!
[INFO]	--> Found desired version locally github.com/tendermint/go-crypto d31cfbaeaa4d930798ec327b52917975f3203c11!
[INFO]	--> Found desired version locally github.com/tendermint/go-wire 5f88da3dbc1a72844e6dfaf274ce87f851d488eb!
[INFO]	--> Found desired version locally github.com/tendermint/tendermint b467515719e686e4678e6da4e102f32a491b85a0!
[INFO]	--> Found desired version locally github.com/tendermint/tmlibs 7ce4da1eee6004d627e780c8fe91e96d9b99e459!
[INFO]	--> Found desired version locally golang.org/x/crypto 7f7c0c2d75ebb4e32a21396ce36e87b6dadc91c9!
[INFO]	--> Found desired version locally golang.org/x/net 02ac38e2528ff4adea90f184d71a3faa04b4b1b0!
[INFO]	--> Found desired version locally golang.org/x/sync f52d1811a62927559de87708c8913c1650ce4f26!
[INFO]	--> Found desired version locally golang.org/x/sys cd2c276457edda6df7fb04895d3fd6a6add42926!
[INFO]	--> Found desired version locally golang.org/x/text 836efe42bb4aa16aaa17b9c155d8813d336ed720!
[INFO]	--> Found desired version locally google.golang.org/genproto b0a3dcfcd1a9bd48e63634bd8802960804cf8315!
[INFO]	--> Found desired version locally google.golang.org/grpc 71260d21715bff9c2ac999d546349d4f4b77ef1d!
[INFO]	--> Found desired version locally gopkg.in/fatih/set.v0 27c40922c40b43fe04554d8223a402af3ea333f3!
[INFO]	--> Found desired version locally gopkg.in/karalabe/cookiejar.v2 8dcd6a7f4951f6ff3ee9cbb919a06d8925822e57!
[INFO]	--> Found desired version locally gopkg.in/natefinch/npipe.v2 c1b8fa8bdccecb0b8db834ee0b92fdbcfa606dd6!
[INFO]	--> Found desired version locally gopkg.in/sourcemap.v1 6e83acea0053641eff084973fee085f0c193c61a!
[INFO]	--> Found desired version locally gopkg.in/urfave/cli.v1 0bdeddeeb0f650497d603c4ad7b20cfe685682f6!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew adab96458c51a58dc1783b3335dcce5461522e75!
[INFO]	--> Found desired version locally github.com/pmezard/go-difflib 792786c7400a136282c1664665ae0a8db921c6c2!
[INFO]	--> Found desired version locally github.com/stretchr/testify 05e8a0eda380579888eb53c394909df027f06991!
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/edsrzf/mmap-go to 0bce6a6887123b67a60366d2c9fe2dfb74289d2e.
[INFO]	--> Setting version for github.com/golang/snappy to 553a641470496b2327abcac10b36396bd98e45c9.
[INFO]	--> Setting version for github.com/go-stack/stack to 54be5f394ed2c3e19dac9134a40a95ba5a017f7b.
[INFO]	--> Setting version for github.com/aristanetworks/goarista to 8ab803d6502ea1e05a8c9b73193b405291efb7ce.
[INFO]	--> Setting version for github.com/huin/goupnp to 73053506a919bb1af6beb97feb0d53a1eb814eb1.
[INFO]	--> Setting version for github.com/go-kit/kit to 69950137349e3e6781c1a54e4f7fd3803bd36765.
[INFO]	--> Setting version for github.com/gorilla/websocket to a69d9f6de432e2c6b296a947d8a5ee88f68522cf.
[INFO]	--> Setting version for github.com/btcsuite/btcd to 47885ab8702485be6b6f87a03d4f3be0bc5c982c.
[INFO]	--> Setting version for github.com/peterh/liner to 88609521dc4b6c858fd4c98b628147da928ce4ac.
[INFO]	--> Setting version for github.com/hashicorp/golang-lru to 0a025b7e63adc15a622f29b0b2c4c3848243bbf6.
[INFO]	--> Setting version for github.com/jackpal/go-nat-pmp to 28a68d0c24adce1da43f8df6a57340909ecd7fdd.
[INFO]	--> Setting version for github.com/golang/protobuf to 0a4f71a498b7c4812f64969510bcb4eca251e33a.
[INFO]	--> Setting version for github.com/karalabe/hid to 875879887cf0560a993b57e04615944e1dd02a73.
[INFO]	--> Setting version for github.com/go-logfmt/logfmt to 390ab7935ee28ec6b286364bba9b4dd6410cb3d5.
[INFO]	--> Setting version for github.com/kr/logfmt to b84e30acd515aadc4b783ad4ff83aff3299bdfe0.
[INFO]	--> Setting version for github.com/pborman/uuid to e790cca94e6cc75c7064b1332e63811d4aae1a53.
[INFO]	--> Setting version for github.com/mattn/go-colorable to 941b50ebc6efddf4c41c8e4537a5f68a4e686b24.
[INFO]	--> Setting version for github.com/fatih/color to 62e9147c64a1ed519147b62a56a14e83e2be02c1.
[INFO]	--> Setting version for github.com/ethereum/go-ethereum to 7db2143396f73f418b50dc5571fec2c62c78b7e4.
[INFO]	--> Setting version for github.com/mattn/go-isatty to fc9e8d8ef48496124e79ae0df75490096eccf6fe.
[INFO]	--> Setting version for github.com/pkg/errors to c605e284fe17294bda444b34710735b29d1a9d90.
[INFO]	--> Setting version for github.com/rcrowley/go-metrics to 1f30fe9094a513ce4c700b9a54458bbb0c96996c.
[INFO]	--> Setting version for github.com/rjeczalik/notify to 88a54d914928e1faebb1c2195605dc87bd98dc27.
[INFO]	--> Setting version for github.com/rs/cors to 8dd4211afb5d08dbb39a533b9bb9e4b486351df6.
[INFO]	--> Setting version for github.com/robertkrimen/otto to 49fee9c1c0db1c366003ede4cc665f9924a97521.
[INFO]	--> Setting version for github.com/spf13/pflag to e57e3eeb33f795204c1ca35f56c44f83227c6e66.
[INFO]	--> Setting version for github.com/syndtr/goleveldb to 8c81ea47d4c41a385645e133e15510fc6a2a74b4.
[INFO]	--> Setting version for github.com/tendermint/go-crypto to d31cfbaeaa4d930798ec327b52917975f3203c11.
[INFO]	--> Setting version for github.com/tendermint/abci to 864d1f80b36b440bde030a5c18d8ac3aa8c2949d.
[INFO]	--> Setting version for github.com/tendermint/ed25519 to 1f52c6f8b8a5c7908aff4497c186af344b428925.
[INFO]	--> Setting version for github.com/tendermint/go-wire to 5f88da3dbc1a72844e6dfaf274ce87f851d488eb.
[INFO]	--> Setting version for github.com/tendermint/tmlibs to 7ce4da1eee6004d627e780c8fe91e96d9b99e459.
[INFO]	--> Setting version for github.com/tendermint/tendermint to b467515719e686e4678e6da4e102f32a491b85a0.
[INFO]	--> Setting version for golang.org/x/crypto to 7f7c0c2d75ebb4e32a21396ce36e87b6dadc91c9.
[INFO]	--> Setting version for golang.org/x/sys to cd2c276457edda6df7fb04895d3fd6a6add42926.
[INFO]	--> Setting version for golang.org/x/net to 02ac38e2528ff4adea90f184d71a3faa04b4b1b0.
[INFO]	--> Setting version for google.golang.org/grpc to 71260d21715bff9c2ac999d546349d4f4b77ef1d.
[INFO]	--> Setting version for google.golang.org/genproto to b0a3dcfcd1a9bd48e63634bd8802960804cf8315.
[INFO]	--> Setting version for golang.org/x/sync to f52d1811a62927559de87708c8913c1650ce4f26.
[INFO]	--> Setting version for golang.org/x/text to 836efe42bb4aa16aaa17b9c155d8813d336ed720.
[INFO]	--> Setting version for gopkg.in/fatih/set.v0 to 27c40922c40b43fe04554d8223a402af3ea333f3.
[INFO]	--> Setting version for github.com/stretchr/testify to 05e8a0eda380579888eb53c394909df027f06991.
[INFO]	--> Setting version for github.com/davecgh/go-spew to adab96458c51a58dc1783b3335dcce5461522e75.
[INFO]	--> Setting version for gopkg.in/natefinch/npipe.v2 to c1b8fa8bdccecb0b8db834ee0b92fdbcfa606dd6.
[INFO]	--> Setting version for github.com/pmezard/go-difflib to 792786c7400a136282c1664665ae0a8db921c6c2.
[INFO]	--> Setting version for gopkg.in/karalabe/cookiejar.v2 to 8dcd6a7f4951f6ff3ee9cbb919a06d8925822e57.
[INFO]	--> Setting version for gopkg.in/sourcemap.v1 to 6e83acea0053641eff084973fee085f0c193c61a.
[INFO]	--> Setting version for gopkg.in/urfave/cli.v1 to 0bdeddeeb0f650497d603c4ad7b20cfe685682f6.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/go-kit/kit
[INFO]	--> Exporting github.com/edsrzf/mmap-go
[INFO]	--> Exporting github.com/ethereum/go-ethereum
[INFO]	--> Exporting github.com/peterh/liner
[INFO]	--> Exporting github.com/go-logfmt/logfmt
[INFO]	--> Exporting github.com/fatih/color
[INFO]	--> Exporting github.com/aristanetworks/goarista
[INFO]	--> Exporting github.com/jackpal/go-nat-pmp
[INFO]	--> Exporting github.com/go-stack/stack
[INFO]	--> Exporting github.com/kr/logfmt
[INFO]	--> Exporting github.com/karalabe/hid
[INFO]	--> Exporting github.com/huin/goupnp
[INFO]	--> Exporting github.com/btcsuite/btcd
[INFO]	--> Exporting github.com/golang/snappy
[INFO]	--> Exporting github.com/mattn/go-colorable
[INFO]	--> Exporting github.com/pborman/uuid
[INFO]	--> Exporting github.com/gorilla/websocket
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/hashicorp/golang-lru
[INFO]	--> Exporting github.com/mattn/go-isatty
[INFO]	--> Exporting github.com/pkg/errors
[INFO]	--> Exporting github.com/rs/cors
[INFO]	--> Exporting github.com/rjeczalik/notify
[INFO]	--> Exporting github.com/rcrowley/go-metrics
[INFO]	--> Exporting github.com/robertkrimen/otto
[INFO]	--> Exporting github.com/tendermint/abci
[INFO]	--> Exporting github.com/spf13/pflag
[INFO]	--> Exporting github.com/syndtr/goleveldb
[INFO]	--> Exporting github.com/tendermint/ed25519
[INFO]	--> Exporting github.com/tendermint/go-crypto
[INFO]	--> Exporting github.com/tendermint/tmlibs
[INFO]	--> Exporting github.com/tendermint/go-wire
[INFO]	--> Exporting github.com/tendermint/tendermint
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/sync
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting github.com/stretchr/testify
[INFO]	--> Exporting github.com/pmezard/go-difflib
[INFO]	--> Exporting google.golang.org/grpc
[INFO]	--> Exporting google.golang.org/genproto
[INFO]	--> Exporting gopkg.in/fatih/set.v0
[INFO]	--> Exporting gopkg.in/karalabe/cookiejar.v2
[INFO]	--> Exporting gopkg.in/natefinch/npipe.v2
[INFO]	--> Exporting gopkg.in/sourcemap.v1
[INFO]	--> Exporting gopkg.in/urfave/cli.v1
[INFO]	Replacing existing vendor dependencies
[INFO]	Removing nested vendor and Godeps/_workspace directories...
[INFO]	Removing: /home/robert/.go/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor
[INFO]	Removing: /home/robert/.go/src/github.com/tendermint/ethermint/vendor/github.com/fatih/color/vendor
[INFO]	Removing: /home/robert/.go/src/github.com/tendermint/ethermint/vendor/github.com/stretchr/testify/vendor
vendor/github.com/ethereum/go-ethereum/interfaces.go:21:2: cannot find package "context" in any of:
	/home/robert/.go/src/github.com/tendermint/ethermint/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/robert/.go/src/context (from $GOPATH)
Makefile:13: recipe for target 'install' failed
make: *** [install] Error 1`

**Comment by rts-2** [comment]
Also: `ls $GOPATH/bin` :
`abci-cli  counter  dummy  glide  gometalinter  megacheck  tendermint  xgo`

**Comment by ebuchman** [comment]
Oh! `cannot find package "context"` Your version of Go is too old. Please update to the latest and try again. As adrian mentioned earlier, we only support version 1.8 and up. You can use the Go version manager if you like: https://github.com/moovweb/gvm

**Comment by rts-2** [comment]
Now when I run a tendermint node it gives me this error, though:
` abci.socketClient failed to connect to tcp`

EDIT: initalization works now though thank you

**Comment by rts-2** [comment]
And If I do an unsafe reset of tendermint, then I end up with a message that says  `panic: Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable`

**Comment by ebuchman** [comment]
It sounds like you have tendermint running already. try `killall tendermint basecoin`. then rerun the reset and try again

**Comment by rts-2** [comment]
Hmm
`basecoin: no process found`

**Comment by ebuchman** [comment]
sorry i meant `killall tendermint ethermint`

**Comment by ebuchman** [comment]
fine if its not found just trying to catch the cases ...

**Comment by rts-2** [comment]
I don't know how, it's a error in the go language?

**Comment by ebuchman** [comment]
hmm? please run the following sequence of commands in full even if some return errors and provide all the output:

```
killall tendermint ethermint
tendermint unsafe_reset_all
tendermint node
```

Now you should see 

```
E[07-28|16:45:02.135] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
```

That's good - tendermint is working and looking for an application to connect to. Now in another terminal run ethermint ...

**Comment by rts-2** [comment]
When I do that it says `ethermint:command not found`

**Comment by ebuchman** [comment]
did you update your Go version and run `make install` in the ethermint dir ? You won't be able to run ethermint until you properly install it. All that should be required is an updated version of Go and running `make install` in the repo.

**Comment by rts-2** [comment]
Yeah, I'm using go1.8, and I did make install in the /tendermint/ethermint directory

**Comment by ebuchman** [comment]
and `make install` worked? 

Can you `ls $GOPATH/bin` again?

**Comment by rts-2** [comment]
bash           fusermount  networkctl        stty
bunzip2        getfacl     nisdomainname     su
busybox        grep        ntfs-3g           sync
bzcat          gunzip      ntfs-3g.probe     systemctl
bzcmp          gzexe       ntfs-3g.secaudit  systemd
bzdiff         gzip        ntfs-3g.usermap   systemd-ask-password
bzegrep        hciconfig   ntfscat           systemd-escape
bzexe          hostname    ntfscluster       systemd-hwdb
bzfgrep        ip          ntfscmp           systemd-inhibit
bzgrep         journalctl  ntfsfallocate     systemd-machine-id-setup
bzip2          kbd_mode    ntfsfix           systemd-notify
bzip2recover   kill        ntfsinfo          systemd-tmpfiles
bzless         kmod        ntfsls            systemd-tty-ask-password-agent
bzmore         less        ntfsmove          tailf
cat            lessecho    ntfstruncate      tar
chacl          lessfile    ntfswipe          tempfile
chgrp          lesskey     open              touch
chmod          lesspipe    openvt            true
chown          ln          pidof             udevadm
chvt           loadkeys    ping              ulockmgr_server
cp             login       ping6             umount
cpio           loginctl    plymouth          uname
dash           lowntfs-3g  ps                uncompress
date           ls          pwd               unicode_start
dd             lsblk       rbash             vdir
df             lsmod       readlink          wdctl
dir            mkdir       red               which
dmesg          mknod       rm                whiptail
dnsdomainname  mktemp      rmdir             ypdomainname
domainname     more        rnano             zcat
dumpkeys       mount       run-parts         zcmp
echo           mountpoint  sed               zdiff
ed             mt          setfacl           zegrep
efibootmgr     mt-gnu      setfont           zfgrep
egrep          mv          setupcon          zforce
false          nano        sh                zgrep
fgconsole      nc          sh.distrib        zless
fgrep          nc.openbsd  sleep             zmore
findmnt        netcat      ss                znew
fuser          netstat     static-sh

**Comment by ebuchman** [comment]
pretty sure that's your `/bin`. Is your GOPATH set?

Please output results of this:

```
go version
echo $GOPATH
echo $GOBIN
echo $PATH
```

Also, can you `cd` to the ethermint repo and run `pwd` ? Thanks.

**Comment by rts-2** [comment]
go version is go1.8.3
echo $GOPATH returns /home/robert/.gvm/pkgsets/go1.8.3/global
echo $GOBIN returns nothing
echo $PATH returns /home/robert/.gvm/pkgsets/go1.8.3/global/bin:/home/robert/.gvm/gos/go1.8.3/bin:/home/robert/.gvm/pkgsets/go1.8.3/global/overlay/bin:/home/robert/.gvm/bin:/home/robert/.gvm/bin:/home/robert/.go/bin:/home/robert/.nvm/versions/node/v6.11.1/bin:/home/robert/bin:/home/robert/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
pwd in ethermint repo returns /home/robert/.gvm/pkgsets/go1.8.3/global/src/github.com/tendermint/ethermint

**Comment by ebuchman** [comment]
very promising!

Can you give us:

```
echo $GOPATH/bin
ls $GOPATH/bin
ls /home/robert/.gvm/pkgsets/go1.8.3/global/bin
```

Also, is there a reason you're trying to install from source? You can download the binary directly from https://tendermint.com/downloads

**Comment by rts-2** [comment]
echo $GOPATH/bin gives me /home/robert/.gvm/pkgsets/go1.8.3/global/bin
ls $GOPATH/bin gives me ethermint  glide  gometalinter  gox  megacheck  tendermint  xgo
ls /home/robert/.gvm/pkgsets/go1.8.3/global/bin gives me 
ethermint  glide  gometalinter  gox  megacheck  tendermint  xgo

**Comment by ebuchman** [comment]
woo!

now `ethermint version` :)

**Comment by rts-2** [comment]
ethermint version
0.4.0-95251185
😳

**Comment by ebuchman** [comment]
so it works ! so what was the problem?

**Comment by rts-2** [comment]
It panicks on a sanity check

**Comment by ebuchman** [comment]
`panic: Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable` ?

**Comment by ebuchman** [comment]
And what panics? Ethermint or Tendermint?

**Comment by rts-2** [comment]
OK, so I fixed the problem, and it was so infuriating. It turns out that whenever I opened a terminal, then the go version would default to go1.6, even if I was in the go1.8.3 directory. To solve the error, you need to delete the old go version off of your computer, and then use gvm to set the right go version. Thanks to everyone who helped me solve this issue.

**Comment by ebuchman** [comment]
Bah! Ok good to know. Thanks for your patience, glad to hear you figured it out.

Hope you enjoy playing with the software :)

**Comment by vanipolnedi** [comment]
maki install_abci is not working for me. any suggestions please. i  am getting error like  **make: *** No rule to make target `install_abci'. Stop** . thanks in advance

**Comment by zramsay** [comment]
@vanipolnedi that make target is for the tendermint repo: https://github.com/tendermint/tendermint/blob/master/Makefile#L57
