### ISSUE TITLE
Transactions not sending from Metamask

### ISSUE THREAD

**Issue by sunnya97** [cosmos/ethermint-archive#214]
Sent ether from geth to metamask account and metamask recognized it.  But transaction send from Metamask isn't going through.

**Comment by kesar** [comment]
The reason is that your genesis.json would probably has a chainID different than the networkId of ethermint. I opened a PR to allow set the networkId :+1:

**Comment by Justin1989** [comment]
Hi @kesar , I compiled and rebuilt ethermint with your pull request. It accepted --neworkid as a parameter. But I still get the same "Invalid sender" error while sending transactions with MetaMask.
Any ideas?

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
