### ISSUE TITLE
Implement a sensible solution for net_version RPC endpoint

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#233]
`net_version` is used by clients to check which network they are connected to. However this doesn't make sense in an ethermint setting. 

We need to decide which of our networks should get which network id and then override the `net_version` RPC endpoint.

This will be related to #178.

**Comment by ratranqu** [comment]
In https://github.com/ethereum/eips/issues/155, the concept of chainId (which seems to be coupled loosely to net_version) is used to generate the signature for transactions, so will need to be thought through carefully.
