### ISSUE TITLE
Implement a network monitor for the underlying tendermint core engine

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#237]
This issue is two fold.

1. Create documentation around how to run a network monitor for the underlying tendermint core engine to any given ethermint network.
3. Host a public tendermint network monitor for our testnets on heroku.

Please refer to #225 for how to create the correct documentation.

This issue is about making it easier to work with the [tm-monitor](https://github.com/tendermint/tools/tree/master/tm-monitor).

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
