### ISSUE TITLE
Create a roadmap for the future development of ethermint

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#24]
Major:
1) get some more comprehensive automated testing and stability
2) address the go-ethereum cruft either by maintaing a fork or pushing the go-eth devs to have more modularity
3) `MinerRewardStrategy` and `ValidatorsStrategy` 
4) add features for private networks like permissioning and white lists for the network layer
5) support interblockchain communication to plug ethermint into cosmos

Other
- cleanup current code
- normalize flags
- better separate sources and other stuff like `dev` `docker` `geth_data`
- better `getting started` documentation
- document architecture
- document known limitations

documentation as part of (1) and fixiing up the flags situation as part of (2)

What are `MinerRewardStrategy` and `ValidatorsStrategy` ?
- the former is a way to figure out who the rewards should go to on each block ... ie how we split them over the validators say
- the latter is to figure out how we make changes to the validator set

**Comment by adrianbrink** [comment]
Consider this: #30

**Comment by adrianbrink** [comment]
Consider this: #32

**Comment by freddyli7** [comment]
`eth_gasPrice` rpc endpoint has been added in #588, but it always returns `0`, currently there is no gas price oracle so that we use default gas price in the code if user doesnt provide it.
