### ISSUE TITLE
Binaries need to ship with the ability to quickly initialise a new network

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#240]
`ethermint start` should be enough to start a new instance. 

The binaries need to ship with default configurations that make this possible. #224 is a step in the right direction but this should be extended.

**Comment by odeke-em** [comment]
@adrianbrink I think we should also consider https://github.com/tendermint/ethermint/issues/213 in which the requested asks that we make `init` implicit when one invokes `ethermint start`.

**Comment by adrianbrink** [comment]
That will also play into it.

**Comment by adrianbrink** [comment]
Closed in favour of #244.
