### ISSUE TITLE
Create "Deploy to Heroku" button

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#243]
A deploy to heroku button should allow the user to automatically deploy ethermint to heroku.

This would mean that the defaults need to be supported better and the biggest ones should be changeable via environment variables.

Generally all cli flags should also be settable through env variables.

Lastly, the `start` command that just starts ethermint with reasonable defaults need to be implemented for this.

This will rely on #244.

**Comment by zramsay** [comment]
feature has not been requested / doesn't really add value
