### ISSUE TITLE
Simplify the initialisation and starting by following the tendermint way

### ISSUE THREAD

**Issue by odeke-em** [cosmos/ethermint-archive#244]
From our Friday Ethermint meeting between @adrianbrink @ebuchman @jaekwon and myself, we realized that currently setting up Ethermint is tricky to do.

## Problem statement
It currently consists of these steps:
1) ```$ tendermint init --home ~/.ethermint/tendermint```
2) ```cd $GOPATH/src/github.com/tendermint/ethermint```
3) ```ethermint --datadir ~/.ethermint init setup/genesis.json```
4) ```cp -r setup/keystore ~/.ethermint```

Notice that steps 2) and 3) require going into the directories and copying a default file.
This dance is tedious even for us the developers of Ethermint. Tendermint is easier to setup
and uses a default file

## Problem solution
Let's make `ethermint init` act like `tendermint init` in which we can optionally specify a a private key validator file, otherwise if the file doesn't exist, we create one and make defaults for it https://github.com/tendermint/tendermint/blob/f8035441951a8d1cbdbc97ba295ea3b85e3c1981/cmd/tendermint/commands/init.go#L23-L43, then serialize it to disk

This will fold steps 2) and 3) into one.

I am on the fence though about whether we should also fold in step 4) Thoughts?

**Comment by odeke-em** [comment]
IMO I vote that we fold steps 2), 3) and 4) into one since by step 3) we've already replaced just one step of having to `cd into $GOPATH/src/github.com/tendermint/ethermint; then using setup/genesis.json`, so it only makes sense to do step 4) otherwise users will still have to `cd there`

**Comment by adrianbrink** [comment]
@odeke-em I agree with you on this one. Could you also generalise the problem description here, since I would like this issue to track the progress on the entire simplification of the initialisation and starting of ethermint.

**Comment by ebuchman** [comment]
>  in which we can optionally specify a a private key validator file

Note we can't really do this, since we're trying to init an ethereum account which is different than a tendermint validator. Perhaps we should integrate with the basecli style key handling though, since I think that lets you make secp256k1 keys

**Comment by odeke-em** [comment]
@ebuchman I see, I'll have to think of how I can implement your suggestion.

**Comment by zramsay** [comment]
would be great of `ethermint/tendermint init` each had `--testnets venus/mercury/etc` flag to write the files (rather than cloning from the `testnets` repo)

**Comment by adrianbrink** [comment]
@zramsay is referring to #179 & #270

**Comment by zramsay** [comment]
yeah, currently [this line](https://github.com/tendermint/ethermint/pull/270/files#diff-b11fe3b7446ef9769750d75324e702b4R26) is false, but it'd be tremendously useful if it were true

**Comment by odeke-em** [comment]
@adrianbrink did you delete your comment in regards to starting `tendermint` as a subprocess? Otherwise I think I recall the excellent suggestion posted up by you.

**Comment by adrianbrink** [comment]
They are in #179
