### ISSUE TITLE
Document the current architecture and possible evolutions

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#251]
The current architectural design should be clearly explained as well as the future direction.

Please refer to #225 to understand how to publish to our new documentation.

# Architecture
- possibly move more and more things into an `internal` package to avoid exposing them

**Comment by ebuchman** [comment]
we have an outline of the current setup here: https://github.com/tendermint/ethermint/tree/master/docs/architecture

so we can start from that and expand. I can add some points on how we plan to handle valset changes and IBC

**Comment by adrianbrink** [comment]
Nice. Let's make sure that we add it into the new docs system.

**Comment by ebuchman** [comment]
Should the low-level architectural design be in the user facing docs? Or better just in repo markdown? If in user-facing docs, need to make sure it's out of the way, or under "advanced" or something

**Comment by adrianbrink** [comment]
Yes, there will be an advanced section. 

The idea though is that everything besides code comments goes into a central documentation.

**Comment by zramsay** [comment]
sufficiently duplicate of #223
