### ISSUE TITLE
Simplify the installation by using brew and other package managers

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#255]
This issue is about making it easier for people to get started with `ethermint` and by extension `tendermint`. 

Currently we have a [brew formula](https://github.com/tendermint/homebrew-tendermint) that installs tendermint and ethermint, however they should be more thoroughly tested and not install from source.

Furthermore, different package managers should also be included here.

**Comment by adrianbrink** [comment]
@Greg-Szabo What is the status for apt?

**Comment by melekes** [comment]
I believe you can now install ethermint using apt. Homebrew formula is almost ready github.com/tendermint/homebrew-tendermint except #357

**Comment by pascalverlinden** [comment]
apt-get install does not seem to work (tried on Ubuntu 16.04.2 LTS.
This produces error "Unable to locate package ethermint".
Is there a PPA to add?

**Comment by zramsay** [comment]
this will come in https://github.com/cosmos/ethermint eventually
