### ISSUE TITLE
Can not build using glide

### ISSUE THREAD

**Issue by ramilexe** [cosmos/ethermint-archive#27]
Run follow commands:

```
go get github.com/Masterminds/glide
go get -d github.com/tendermint/ethermint
cd /go/src/github.com/tendermint/ethermint
glide install
cd cmd/ethermint/
go build
```

and get error:

```
../../ethereum/node.go:21: cannot use ctx (type *"github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli.v1".Context) as type *"github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1".Context in argument to utils.MakeDataDir
```

I am building using glide but in your docs and Dockerfile you just do 
`go get github.com/tendermint/ethermint/cmd/ethermint`

Why do you have `glide.lock` if you don't use it?

**Comment by ebuchman** [comment]
We decided to check in the vendor folder for now to ease install for users. Once we start publishing binaries for ethermint, we will remove it and use glide properly again.

**Comment by adrianbrink** [comment]
Oh, this is good to know :-) thank @ramilexe

**Comment by ltzmaxwell** [comment]
use glide install -v simply to remove nested vendor , will be working good.

**Comment by ramilexe** [comment]
@ltzMaxwell yes, it set in makefile https://github.com/tendermint/ethermint/blob/master/Makefile#L37
