### ISSUE TITLE
Write a guide on how to run a private instance in 2 easy steps

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#277]
- [ ] Test it with 2 users that have never used ethermint or venus and just watch them follow the guide. Then update accordingly

**Comment by okwme** [comment]
The install from source instructions in `README.md` worked with only minor hangups for me (gvm wasn't happy that I had already installed go with homebrew and that GOPATH wasn't set). I'm still a little lost on how to interact with ethermint from here on out though.

**Comment by zramsay** [comment]
@okwme see https://github.com/tendermint/ethermint/blob/develop/docs/getting-started.md 
and https://github.com/tendermint/ethermint/pull/270 - happy for any comments on either

**Comment by adrianbrink** [comment]
Add the sequence of commands needed.

**Comment by zramsay** [comment]
@adrianbrink this is blocking on the sequence of commands required (a bash test, basically)

**Comment by zramsay** [comment]
guide should include info on updating the validator set

**Comment by zramsay** [comment]
https://github.com/b00f/ethermint-private-network (looks like only one node FTTB)

**Comment by zramsay** [comment]
will eventually be addressed in https://github.com/cosmos/ethermint
