### ISSUE TITLE
Harmonise the log levels between ethermint, tendermint and go-ethereum

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#28]
- `tendermint` logging technology and `log_level` flag
- `ethereum` logging technology and `verbosity` flag
- `ethermint`, use one of above, which one, logging level flag ?

**Comment by illya13** [comment]
- `tendermint`:
    - `github.com/tendermint/go-logger`
    - `log_level` flag

- `ethereum`:
    - `github.com/ethereum/go-ethereum/logger`
    - `github.com/ethereum/go-ethereum/logger/glog`
    - no flag, add support of `verbosity` ?

- `ethermint`:
    - follows `Ethereum`
    - `github.com/ethereum/go-ethereum/logger`
    - `github.com/ethereum/go-ethereum/logger/glog`
    - no flag, add support of `verbosity` ?

- `--verbosity value`
    - Logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=core, 5=debug, 6=detail (default: 3)

- `--vmodule value`
    - Per-module verbosity: comma-separated list of <pattern>=<level> (e.g. eth/*=6,p2p=5)

- `logger.AddLogSystem(logger.NewStdLogSystem(os.Stdout, log.LstdFlags, logger.DebugLevel))`
    - ?

**Comment by jaekwon** [comment]
At first pass, I think we should expose verbosity as a flag.
Where is the ethereum log going to?

**Comment by illya13** [comment]
you mean `STDERR` or `STDOUT` ?

**Comment by ramilexe** [comment]
@jaekwon don't we want to synchronize `tendermint` `log_level` flag and `ethereum` `verbosity` flag?

**Comment by ebuchman** [comment]
Tendermint logging is being overhauled for 0.10. We should wait until then to move on this.
