### ISSUE TITLE
Write a guide that explains how to use go to deploy and interact with smart contracts using abigen

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#281]
go-ethereum has a tool called [abigen](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts) that can be used to generate go bindings for smart contracts and use those bindings to interact with them. 

We should write a guide on how that integrates with ethermint.

**Comment by sivachaitanya** [comment]
Ok so I'm goinf through your Medium and Documentation example, Basically you are removing the consensus from Ethereum which Tendermint Core would handle that using POS ? and if I have a Solidity smart contract say a simple read and write of string how would I deploy that if I'm using Ethermint and should I use web3 to interact with my contract or ABCI end points to interact with it ? Thanks for the great tool

**Comment by adrianbrink** [comment]
You can interact with Ethermint through all the normal web3 tooling.

The only difference is that instead of starting an Ethereum instance you start an Ethermint instance.

**Comment by sivachaitanya** [comment]
Great now that explains the difference of separation of POW consensus from Ethereum which will be handled by Tendermint Core in the Ethermint, so all I need to do is write by same web3 script which targets the geth of Ethermint and simultaneously experiencing high Tx speeds :-) , great job you guys !

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
