### ISSUE TITLE
Implement '--testnet' flag that allows users to connect to the venus testnet

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#282]
A user should be able to run `ethermint --testnet` and automatically be connected to one of our testnets. The user should not have to initialise ethermint or tendermint. However he should be able to specify other useful options such as which RPC endpoints to open.

**Comment by zramsay** [comment]
it's a nice idea but probably not worth the tech debt, especially if we have clear joining testnet instructions
