### ISSUE TITLE
Create a tool to snapshot other blockchains such as ethereum classic

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#289]
This tool should allow the exporting of the account state into a new genesis.json file.

**Comment by odeke-em** [comment]
For starters, could we collect a list of other blockchains that we'd like to support:
- [ ] Ethereum Classic
- [ ] Ethereum
- [ ] Bitcoin
...

Please feel free to edit and add more

**Comment by zramsay** [comment]
if it's a tool it would be in the tools repo. also, not a requested feature
