### ISSUE TITLE
Allow configuring `targetgaslimit` and propogate that block size to Tendermint Core

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#300]

**Comment by odeke-em** [comment]
@adrianbrink could you please elaborate on what you are requesting in this issue?
I don't have any context here unfortunately but I'd like to follow along with this issue and I'd assume other developers might too :)

Do you mean, support changing the gaslimit dynamically? Changed by whom? How?

If on the commandline there is flag `--targetgaslimit` which am sure you are aware about.

Currently there is a usage of TargetGasLimit in ethereum but that's capped at `4712388` as per
https://github.com/ethereum/go-ethereum/blob/9be07de5396527eb527f3ca0dd402213c0008a3e/params/protocol_params.go#L77
and set at
https://github.com/ethereum/go-ethereum/blob/9be07de5396527eb527f3ca0dd402213c0008a3e/params/protocol_params.go#L78

**Comment by adrianbrink** [comment]
Tendermint does not have a notion of gas limit. It just has a limit on the number of transactions per block. This means that when Tendermint has a tx limit of 1000 per block it will try to put that many into a single Ethermint block. However these transactions might be very large (have a high gas usage) and hence 1000 of those will exceed the TargetGasLimit of Ethermint. 

Since Tendermint decides on the block with all its transactions before actually running the block, it can cause a lot of invalid transactions to be included in a single Tendermint block. It would be great if somehow the ABCI can let Tendermint know about its own max block size. I am not sure yet how to do this.

A good starting point for this issue would be to produce a test case. Something along the lines of running Ethermint, and submitting 1000 really large transactions and see what happens. Currently, this issue is purely theoretical since I thought about it while travelling. @odeke-em Do you think it is something that you can tackle?

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
