### ISSUE TITLE
blockchain synchronization stuck on Tendermint level while monitored by eth-net-intelligence-api

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#313]
- no errors in log
- now new blocks propagated

**Comment by odeke-em** [comment]
@illya13 thanks for reporting the issue.
Could you please provide some more context on what you did? How can one try to reproduce this?

**Comment by illya13** [comment]
Sorry I don't have much details
- we had 4 nodes network running for 3 months
- then I tried to increase `targetgaslimit` over one of the nodes
- broke local storage, had to clean up everything and restart
- now this one node is syncing and periodically just stuck

Some stats:
- total blocks: 5,837,447
- usually stuck each 15-30 mins
- no errors in logs

Work around:
cron job to restart all
```0,30 */1 * * * restart.sh```

```
killall -9 ethermint tendermint
sleep 3
nohup ethermint --datadir .ethermint ...
tendermint node --home .ethermint/tendermint ...
```

**Comment by illya13** [comment]
- ethermint: **v0.2.0**
- tendermint: **v0.10.0**

**Comment by odeke-em** [comment]
Awesome, thank you for providing as much repro information as you could. I have alerted the rest of the team about this issue.

**Comment by illya13** [comment]
All network nodes are monitored by modified `eth-netstats` & `eth-net-intelligence-api`.
Question is -  can modified `eth-netstats` monitoring affect stability of network ?

**Comment by illya13** [comment]
@ebuchman 
https://github.com/tendermint/tendermint/blob/9af837c24d2223bc98c2859dcebcb2398a2c35c2/mempool/mempool.go#L305

Can this be an issue knowing that `eth-net-intelligence-api` very aggressive calls `Reap`

**Comment by adrianbrink** [comment]
@illya13 Does the `eth-net-intelligence-api` call directly into `Reap`?

**Comment by illya13** [comment]
not directly, through 
https://github.com/tendermint/eth-net-intelligence-api/blob/master/lib/node.js#L574
and
https://github.com/tendermint/tendermint/blob/9af837c24d2223bc98c2859dcebcb2398a2c35c2/rpc/core/mempool.go#L232

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
