### ISSUE TITLE
Error: timestamp equals parent's

### ISSUE THREAD

**Issue by tianyaqpzm** [cosmos/ethermint-archive#315]
Hi, I got an error, Once ethermint state update fails, Single node will crash～～～how to solve the problems??   I don't want to clean up the data. Thx.~~~~~~

tendermint:
E[09-28|06:32:34.831] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
I[09-28|06:39:45.330] Starting socketClient                        module=abci-client connection=mempool impl=socketClient
I[09-28|06:39:50.506] Starting socketClient                        module=abci-client connection=consensus impl=socketClient
I[09-28|06:39:55.419] ABCI Handshake                               module=consensus appHeight=94 appHash=CC6BB74E02A4F1EF10E9DAA9E871A017E80C2631ED53EA167022E8F4BCF428E7
I[09-28|06:39:56.049] ABCI Replay Blocks                           module=consensus appHeight=94 storeHeight=95 stateHeight=94
I[09-28|06:40:02.418] Replay last block using real app             module=consensus 
I[09-28|06:40:37.641] Executed block                               module=state height=95 validTxs=1 invalidTxs=0
E[09-28|06:41:05.800] Error in proxyAppConn.CommitSync             module=state err="ABCI{code:InternalError, data:, log:Internal error;timestamp equals parent's}"
Error starting proxy app connections: Error on replay: Commit failed for application: ABCI{code:InternalError, data:, log:Internal error;timestamp equals parent's}

ethermint:
DEBUG[09-28|14:41:03] Trie cache stats after commit            misses=8 unloads=0
header.Time:  1506474801
blockHash: 0000000000000000000000000000000000000000000000000000000000000000
ERROR[09-28|14:41:03] 
########## BAD BLOCK #########
Number: 95
Error: timestamp equals parent's
##############################
ERROR[09-28|14:41:03] Error getting latest ethereum state      module=ethermint   err="timestamp equals parent's"

**Comment by adrianbrink** [comment]
What kind of setup are you running? What's your OS, which versions of Tendermint and Ethermint are you using and what are the steps that lead you to this error?

**Comment by tianyaqpzm** [comment]
OS：macOS Sierra 10.12.2
Tendermint 0.10.4   
Ethermint 0.4  develop
I wanted to store the transactionTX after consensus，Firstly，I modified the DeliverTx in ethermint, then resulting in abnormal exit, After restored DeliverTx ，the error occurred.

**Comment by adrianbrink** [comment]
So you want to store the transaction in a separate database after it has passed through consensus?

Can you show me the modified version of deliverTx?

**Comment by tianyaqpzm** [comment]
@adrianbrink 
Yeah, the code is the flollowing.

func (app *EthermintApplication) DeliverTx(txBytes []byte) abciTypes.Result {
	tx, err := decodeTx(txBytes)
	fmt.Println("tx:",tx)
	if err != nil {
		app.logger.Debug("DelivexTx: Received invalid transaction", "tx", tx, "err", err) // nolint: errcheck
		return abciTypes.ErrEncodingError.AppendLog(err.Error())
	}
	app.logger.Debug("DeliverTx: Received valid transaction", "tx", tx) // nolint: errcheck

	err = app.backend.DeliverTx(tx)
	if err != nil {
		app.logger.Error("DeliverTx: Error delivering tx to ethereum backend", "tx", tx, "err", err) // nolint: errcheck
		return abciTypes.ErrInternalError.AppendLog(err.Error())
	}
	app.CollectTx(tx)

	// store to mysql   
	p := tx.ToMysql();
	fmt.Println(p)
	return abciTypes.OK
}

func (tx *Transaction) ToMysql() int64 {
	var from, to string
	if tx.data.V != nil {
		// make a best guess about the signer and use that to derive
		// the sender.
		signer := deriveSigner(tx.data.V)
		if f, err := Sender(signer, tx); err != nil { // derive but don't cache
			from = "[invalid sender: invalid sig]"
		} else {
			from = fmt.Sprintf("%x", f[:])
		}
	} else {
		from = "[invalid sender: nil V field]"
	}

	if tx.data.Recipient == nil {
		to = "[contract creation]"
	} else {
		to = fmt.Sprintf("%x", tx.data.Recipient[:])
	}
	enc, _ := rlp.EncodeToBytes(&tx.data)
	//strconv.ParseInt(b, 2, 10)
	var isContract int
	if len(*tx.data.Recipient) == 0{
		isContract =1
	}else{
		isContract =0
	}

	return pei.InsertInto(tx.Hash().String(),isContract,from,to,tx.data.AccountNonce,tx.data.Price.String(),		tx.data.GasLimit.String(),tx.data.Amount.String(),tx.data.Payload,tx.data.V.String(),tx.data.R.String(),tx.data.S.String(), enc)
}

func InsertInto(TX string, isContract int, From string, To string, Nonce uint64,GasPrice string,
	GasLimit string,Value string, Data []byte, V string,R string,S string, Hex []byte) int64{
	stmt, err := db.Prepare(`INSERT tm (TX, tm_From,tm_To,Nonce,Value,Contract,GasPrice,GasLimit,Data,V,R,S,Hex) values (?,?,?,?,?,?,?,?,?,?,?,?,?)`)
	if err != nil{
		fmt.Println(err)
		os.Exit(-1)
	}
	//fmt.Println(string(TX))
	res, err := stmt.Exec(string(TX), From, To,Nonce,Value,isContract,GasPrice,GasLimit,Data,V,R,S,Hex)
	if err != nil{
		fmt.Println(err)
		os.Exit(-1)
	}
	fmt.Println(res)
	id, err := res.LastInsertId()
	return id
}

**Comment by tianyaqpzm** [comment]
@adrianbrink  
Yeah, i just begin to learn and test, ~~~~ This is code:
```
func (app *EthermintApplication) DeliverTx(txBytes []byte) abciTypes.Result {
	tx, err := decodeTx(txBytes)
	fmt.Println("tx:",tx)
	if err != nil {
		app.logger.Debug("DelivexTx: Received invalid transaction", "tx", tx, "err", err) // nolint: errcheck
		return abciTypes.ErrEncodingError.AppendLog(err.Error())
	}
	app.logger.Debug("DeliverTx: Received valid transaction", "tx", tx) // nolint: errcheck

	err = app.backend.DeliverTx(tx)
	if err != nil {
		app.logger.Error("DeliverTx: Error delivering tx to ethereum backend", "tx", tx, "err", err) // nolint: errcheck
		return abciTypes.ErrInternalError.AppendLog(err.Error())
	}
	app.CollectTx(tx)

	// store to mysql
	p := tx.ToMysql();
	fmt.Println(p)
	return abciTypes.OK
}

func (tx *Transaction) ToMysql() int64 {
	var from, to string
	if tx.data.V != nil {
		// make a best guess about the signer and use that to derive
		// the sender.
		signer := deriveSigner(tx.data.V)
		if f, err := Sender(signer, tx); err != nil { // derive but don't cache
			from = "[invalid sender: invalid sig]"
		} else {
			from = fmt.Sprintf("%x", f[:])
		}
	} else {
		from = "[invalid sender: nil V field]"
	}

	if tx.data.Recipient == nil {
		to = "[contract creation]"
	} else {
		to = fmt.Sprintf("%x", tx.data.Recipient[:])
	}
	enc, _ := rlp.EncodeToBytes(&tx.data)
	//strconv.ParseInt(b, 2, 10)
	var isContract int
	if len(*tx.data.Recipient) == 0{
		isContract =1
	}else{
		isContract =0
	}

	return pei.InsertInto(tx.Hash().String(),isContract,from,to,tx.data.AccountNonce,tx.data.Price.String(),
			tx.data.GasLimit.String(),tx.data.Amount.String(),tx.data.Payload,tx.data.V.String(),tx.data.R.String(),tx.data.S.String(), enc)

}

func InsertInto(TX string, isContract int, From string, To string, Nonce uint64,GasPrice string,
	GasLimit string,Value string, Data []byte, V string,R string,S string, Hex []byte) int64{
	stmt, err := db.Prepare(`INSERT tm (TX, tm_From,tm_To,Nonce,Value,Contract,GasPrice,GasLimit,Data,V,R,S,Hex) values (?,?,?,?,?,?,?,?,?,?,?,?,?)`)
	if err != nil{
		fmt.Println(err)
		os.Exit(-1)
	}
	//fmt.Println(string(TX))
	res, err := stmt.Exec(string(TX), From, To,Nonce,Value,isContract,GasPrice,GasLimit,Data,V,R,S,Hex)
	if err != nil{
		fmt.Println(err)
		os.Exit(-1)
	}
	fmt.Println(res)
	id, err := res.LastInsertId()
	return id
}
```

**Comment by marfvr** [comment]
I had the same problem. Maybe It's my setup that is wrong.
`tendermint: 0.14.0`
`ethermint:  0.5.3-ea61396`
`go-ethereum:  1.6.7-stable`
`uname -a: Linux 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

I use an ethermint application on 4 tendermint nodes.

- The `genesis.json` file for each tendermint node is:

        {
	   "app_hash" : "",
	   "genesis_time" : "2018-01-26T01:22:09.999297398+01:00",
	   "validators" : [
	      {
		 "pub_key" : {
		    "data" : "469335BDAA78F4CA9264A4720DD02AC13BEF17BBD2DC9F7974D9B002DBA2765A",
		    "type" : "ed25519"
		 },
		 "name" : "mach0",
		 "power" : 1
	      },
	      {
		 "power" : 1,
		 "pub_key" : {
		    "type" : "ed25519",
		    "data" : "6A5B60E122FDC072C9DA9B5250E97BD34C22CC49BB5ABF7F657B7BB823885FF4"
		 },
		 "name" : "mach1"
	      },
	      {
		 "name" : "mach2",
		 "pub_key" : {
		    "data" : "623A1F5963A1B98D7A1BBD4FCDD6C3A7D0F0E0C15236E83F2C10FB52BF67A833",
		    "type" : "ed25519"
		 },
		 "power" : 1
	      },
	      {
		 "name" : "mach3",
		 "pub_key" : {
		    "type" : "ed25519",
		    "data" : "6D326318C2DAF9F1B6503BB38DE29B1530D0EFDBA89E9354024B6D4DA15C7304"
		 },
		 "power" : 1
	      }
	   ],
	   "chain_id" : "chain-dYEq57"
	    }

    the testnet is generated through the `tendermint testnet` utility.



- The network is organized as follows: each node from `0` to `3` has `rpc.laddr="tcp://0.0.0.0:466X7"`, `p2p.laddr="tcp://0.0.0.0:466X6"` and as seeds the other three nodes p2p addresses.

- the `ethermint` app is launched after that every node is started. The command is the following:

        ethermint --datadir .ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin --tendermint_addr "tcp://0.0.0.0:46607"

Notice `--tendermint_addr` pointing to node 0.

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint for latest ethermint
