### ISSUE TITLE
Combine Tendermint and Ethermint genesis files

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#317]
Ethermint has a different genesis file to initialise the Ethermint instance. It uses the same genesis file for the Tendermint instance though. What is supposed to be in the app_options part? Is that ignored by Tendermint? Because we could write a transformation that takes an Ethermint and a Tendermint genesis file and combines them both into one file, where all the Ethermint options are under app_options. However, that would mean that we need to change the genesis file decoding for Ethermint.

This is from a slack conversation and might be a sweet usability improvement.

**Comment by melekes** [comment]
> Is that ignored by Tendermint?

yes

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint will have a nice solution i'm sure
