### ISSUE TITLE
--with-tendermint flag provided but not defined

### ISSUE THREAD

**Issue by betheone5** [cosmos/ethermint-archive#319]
Hi

Latest release document about [Ethermint](https://media.readthedocs.org/pdf/ethermint/develop/ethermint.pdf), a new flag is introduced "--with-tendermint". I was trying to use that while starting ethermint like this

ethermint --with-tendermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpccorsdomain "*" --unlock 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc --password ~/.ethermint/password.txt

But i see the following error in the terminal.
flag provided but not defined: -with-tendermint

I have installed Ethermint version (0.4.0-95251185) and Tendermint version (0.11.0-7682ad9a)

**Comment by adrianbrink** [comment]
@betheone5 That is correct. The flag will only appear in 0.5.0. Sorry about the mismatch with the documentation.

**Comment by zramsay** [comment]
The link to the docs provided is for the develop branch. If you build ethermint from source using that branch, the flag will work.
