### ISSUE TITLE
Ethereum features to control / disable

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#32]
Document and enhance control of Ethereum features
- [x] PoW
    - code, set `fakePoW`
- [ ] block size control by gas
    - can be controlled by Ethereum `gaslimit` and Tendermint `block_size`
- [x] P2P
    - code, set `--nodiscover`, `--maxpeers 0`
- [x] keeping `tx` in order
    - code patch, https://github.com/tendermint/ethermint/pull/42
- [x] mining API
    - code, filtered API
    - TODO: test over other endpoints: ws, ipc
- [x] `pending block` support
    - code patch, https://github.com/tendermint/ethermint/pull/42

**Comment by illya13** [comment]
P2P command line flags are not supported and code is missing - TODO: PR

**Comment by illya13** [comment]
a lot of solved in https://github.com/tendermint/ethermint/pull/42

**Comment by ebuchman** [comment]
@illya13 so to solve this gas limit issue, should we just set the default tendermint block_size to 100 and the default target gas limit for ethereum to 10 million? Then we shouldnt have to provide any flags to get a reasonable setting, and we can document how people can adjust.

**Comment by ebuchman** [comment]
@illya13 so to solve this gas limit issue, should we just set the default tendermint block_size to 100 and the default target gas limit for ethereum to 10 million? Then we shouldnt have to provide any flags to get a reasonable setting, and we can document how people can adjust.

**Comment by illya13** [comment]
Ok with `500` and ‭`0x10000000‬`.
( IMO we need to have `500tx/s` as a target performance )
But ‭`0x10000000‬` needs to be used in genesis and as a default value for `--targetgaslimit`

**Comment by ramilexe** [comment]
Isn't issue with `params.MinGasLimit` https://github.com/tendermint/go-ethereum/blob/master/core/block_validator.go#L356 ?
When block gas limit can decrease to this value?
