### ISSUE TITLE
Error flushing consensus wal buf to file. Error: invalid argument \n"

### ISSUE THREAD

**Issue by betheone5** [cosmos/ethermint-archive#320]
I have installed tendermint and ethermint and it was working fine. But all of a sudden i see the following error in the tendermint console. Now the transactions are not processed even after i restart both tendermint and ethermint. 

Any suggestions will be appreciated

**Comment by adrianbrink** [comment]
@betheone5 Could you paste the entire console output that you get?

**Comment by betheone5** [comment]
Here are the logs.

I[10-10|11:09:25.358] Executed block                               module=state height=52704 validTxs=0 invalidTxs=0
I[10-10|11:09:25.365] Committed state                              module=state height=52704 txs=0 hash=790D9058DCDFBB469E87F7D65D8ADE6AB9FB7D4AD0DC62A538DFF6BDE3535088

E[10-10|11:09:26.342] CONSENSUS FAILURE!!!                         module=consensus err="Panicked questionably: Error flushing consensus wal buf to file. Error: invalid argument \n"

**Comment by adrianbrink** [comment]
What version of Tendermint and Ethermint are you on?

Run:
```
tendermint version
ethermint version
```

**Comment by betheone5** [comment]
tendermint version
0.11.0-7682ad9a

ethermint version
0.4.0-95251185

**Comment by zhangyelong** [comment]
@adrianbrink Same problem
tendermint version
0.11.0-925696ca
ethermint version
ethermint:  0.5.0-4f7132ba
go-ethereum:  1.6.7-stable

**Comment by melekes** [comment]
I would recommend to upgrade Tendermint to https://github.com/tendermint/tendermint/releases/tag/v0.12.1

**Comment by zramsay** [comment]
stale, closing. Please re-open if you encounter the issue using the latest versions of tendermint and ethermint
