### ISSUE TITLE
go install issue

### ISSUE THREAD

**Issue by danieljbruce** [cosmos/ethermint-archive#348]
when running the following in terminal:
go get -u -d github.com/tendermint/ethermint

I get the following result:
package github.com/tendermint/ethermint: no Go files in /Users/funuser/go/src/github.com/tendermint/ethermint

**Comment by adrianbrink** [comment]
That is normal. Currently we don't support installation using `go get`. After running the above command you can navigate to `$GOPATH/src/github.com/tendermint/ethermint` and run `make install`.
