### ISSUE TITLE
Can not create network with ethermint

### ISSUE THREAD

**Issue by ramilexe** [cosmos/ethermint-archive#35]
Trying to create network with ethermint.

Generate two init dirs with the same genesis.json:
`ethermint --datadir $ROOT_DIR/mach0 init genesis.json` and 
`ethermint --datadir $ROOT_DIR/mach1 init genesis.json` 
(idea taken from here https://github.com/tendermint/ethermint/tree/automatic_tests/test/p2p)

Then copy `mach1` to another node and run on node 0:
`ethermint --datadir /root/.ethermint/mach0`
and on node 1:
`ethermint --seeds=<node0-ip-address>:46656 --datadir ~/.ethermint/mach1`

In both logs (node0 and node1) see follow error:
```
Error: runtime error: invalid memory address or nil pointer dereference
Stack: goroutine 144 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p.(*MConnection)._recover(0xd7a125a0)
	/go/src/github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p/connection.go:173 +0x43
panic(0x8a7e860, 0xd7782008)
	/usr/local/go/src/runtime/panic.go:458 +0x40b
sync/atomic.LoadUint64(0xd7a125dc, 0xd79bd708, 0xd7a782c0)
	/usr/local/go/src/sync/atomic/asm_386.s:159 +0xb
github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p.(*MConnection).sendSomeMsgPackets(0xd7a125a0, 0xd7a782c0)
	/go/src/github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p/connection.go:317 +0x2f
github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p.(*MConnection).sendRoutine(0xd7a125a0)
	/go/src/github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p/connection.go:288 +0x67f
created by github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p.(*MConnection).OnStart
	/go/src/github.com/tendermint/ethermint/vendor/github.com/tendermint/go-p2p/connection.go:137 +0x160
```

**Comment by ramilexe** [comment]
Investigated this problem. I run ethermint on 32 bit machine and get error here https://github.com/tendermint/go-p2p/blob/master/connection.go#L317
`atomic.LoadInt64`

**Comment by illya13** [comment]
so let's document and close this one ?

**Comment by ebuchman** [comment]
This seems like a tendermint issue. will open there.
