### ISSUE TITLE
Question: can we add Ethermint nodes while keep the system running?

### ISSUE THREAD

**Issue by Andlinks-Yourturn** [cosmos/ethermint-archive#356]
## Description
*Please describe the issue as detailed as possible.*
Hello, there

I am trying to migrate my private Ethereum blockchain to Ethermint, and I have some problems of setting up the network. 
It appears that all the Nodes are determined pre-genesis. While, I'd love to make it possible to join the Ethermint network after genesis. Is there already a guide or hint to achieve this?

Thanks so much.

**Comment by zramsay** [comment]
Are you trying to join the existing testnet with a single node (that's yours) or setup your own testnet? (with multiple nodes that are yours)

**Comment by Andlinks-Yourturn** [comment]
Yes @zramsay , I set up my own testnet. 
I see there's a function for updating 
`// GetUpdatedValidators returns an updated validator set from the strategy
// #unstable
func (app *EthermintApplication) GetUpdatedValidators() abciTypes.ResponseEndBlock {
	if app.strategy != nil {
		return abciTypes.ResponseEndBlock{Diffs: app.strategy.GetUpdatedValidators()}
	}
	return abciTypes.ResponseEndBlock{}
}`

**Comment by melekes** [comment]
I don't know Ethermint that good, but I know it's totally possible in Tendermint and since Ethermint is built on top of it, it should be possible with Ethermint. See this file https://github.com/tendermint/ethermint/blob/master/strategies/validators/tx_based.go#L39. Maybe this is what you are looking for.

**Comment by zramsay** [comment]
see https://github.com/tendermint/ethermint/issues/277#issuecomment-363965844
