### ISSUE TITLE
Remove block gaslimit

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#361]
Block gaslimit should sit on the Tendermint Core side. The app side does not need to care about block gaslimit.

**Comment by urugang** [comment]
upvote! 
in our performance test, tendermint deliver tx to ethermint; then ethermint reach its block gas limit, so return back outOfGasLimit, then tendermint put that tx into invalid state. Here the tx is not valid for current block, but will be valid for next block.

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
