### ISSUE TITLE
Installation fails on Mac OSX: file not found

### ISSUE THREAD

**Issue by zhangyelong** [cosmos/ethermint-archive#362]
#### $ go install ./cmd/ethermint/
\# github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:10:10: fatal error: 'CoreServices/CoreServices.h' file not found
\#include <CoreServices/CoreServices.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
\# github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid
In file included from vendor/github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid/hid_enabled.go:38:
./hidapi/mac/hid.c:25:10: fatal error: 'IOKit/hid/IOHIDManager.h' file not found
\#include <IOKit/hid/IOHIDManager.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
\# github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
In file included from vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/secp256.go:29:
In file included from ././libsecp256k1/src/secp256k1.c:9:
vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/libsecp256k1/src/util.h:14:10: fatal error: 'stdlib.h' file not found
\#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.

## Environment
Mac OS Version: 10.13.1
GO Version: 1.9.2

**Comment by melekes** [comment]
```
make get_vendor_deps
make install
```

**Comment by zhangyelong** [comment]
@melekes Thanks for replying, but it still not working

**Comment by melekes** [comment]
Duh, sorry. What version of ethermint? Did you try `develop` branch?

**Comment by zhangyelong** [comment]
The newest version, and I've tried `develop` branch.
```
$ git pull
warning: redirecting to https://github.com/tendermint/ethermint/
Already up-to-date.
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.

nothing to commit, working tree clean
```

**Comment by melekes** [comment]
Ye, but have you tried `make build` or `make install` or `CGO_ENABLED=1 go install ./cmd/ethermint/`?

**Comment by zhangyelong** [comment]
Yes，I've tried everything I can, `make build`, `make install` and `glide install`, `go install ./cmd/ethermint/` and `make get_vendor_deps` etc...Not working on branch `master` nor `develop`
But it works well on Ubuntu.

**Comment by zhangyelong** [comment]
I got it, I didn't install the `XCode Command Line Tools`, run:
```
xcode-select --install
```
and restart the terminal.

**Comment by zramsay** [comment]
yeah, xcode is  pretty important :)

**Comment by melekes** [comment]
Should we add this to the readme?

**Comment by EnchanterIO** [comment]
I had a similar issue with:

> tendermint git:(master) make install
> go install -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD`" -tags 'tendermint' ./cmd/tendermint
> consensus/state.go:12:2: cannot find package "github.com/ebuchman/fail-test" in any of:
> 	/usr/local/go/src/github.com/ebuchman/fail-test (from $GOROOT)
> 	/Users/llukac/Development/go/src/github.com/ebuchman/fail-test (from $GOPATH)
> rpc/lib/server/handlers.go:17:2: cannot find package "github.com/gorilla/websocket" in any of:
> 	/usr/local/go/src/github.com/gorilla/websocket (from $GOROOT)
> 	/Users/llukac/Development/go/src/github.com/gorilla/websocket (from $GOPATH)

I solved it by installing glide:

`brew install glide`

then running whatever this does:

`make get_vendor_deps` 

and at the end i was finally able to run:

`make install`

I think this should be added to the Readme. I can create the PR if u want to.
