### ISSUE TITLE
Problem with genesis.json while using documentation for testnets

### ISSUE THREAD

**Issue by alienatorZ** [cosmos/ethermint-archive#367]
Following the steps in docs/testnets/venus.rst 

On the step:$  tendermint --home ~/.venus/tendermint node I get the error:

Failed to create node: Error reading GenesisDoc at /home/ooo/.venus/tendermint/geneses.json: The genesis file cannot contain validators with no voting power: 

it then lists the first validator in genesis file.

**Comment by zramsay** [comment]
the venus testnet no longer exists and those docs will be updated.

**Comment by gkapkowski** [comment]
@zramsay Hi, is there other testnet functioning right now? Where should I look for updates/testnet status?

**Comment by zramsay** [comment]
will be fixed in https://github.com/cosmos/ethermint
