### ISSUE TITLE
Upgrade go-ethereum to 1.7.3 (1.8.0)

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#368]
```go-ethereum``` release ```1.7.x``` has number of performance improvements
* https://github.com/ethereum/go-ethereum/releases/tag/v1.7.0
* https://github.com/ethereum/EIPs/pull/706
* https://github.com/ethereum/go-ethereum/pull/15106

It would be nice to have it as well

/ CC @jaekwon @ebuchman @adrianbrink @melekes

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint
