### ISSUE TITLE
Upgrade tendermint to the latest

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#369]
Seems like ```tendermint``` version used in ```ethermint``` is already too old

/ CC @jaekwon @ebuchman @adrianbrink @melekes

**Comment by zramsay** [comment]
this'll also need to update to the new config configuration

**Comment by adanielyan** [comment]
Is there any work in progress on this?

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint
