### ISSUE TITLE
 Waiting for tendermint endpoint to start err="Post http://localhost:46657/status: dial tcp 127.0.0.1:46657: getsockopt: connection refused"

### ISSUE THREAD

**Issue by baffonso** [cosmos/ethermint-archive#377]
when starting up ethermint and tendermint the following message is repeated in the ethermint log:

INFO [01-17|22:07:27] Waiting for tendermint endpoint to start err="Post http://localhost:46657/status: dial tcp 127.0.0.1:46657: getsockopt: connection refused"

**Comment by baffonso** [comment]
If i set proxy_app to dummy (tendermint --home ~/.ethermint/tendermint node --proxy_app=dummy)
ethermint is able to start up fine

**Comment by zramsay** [comment]
you shouldn't have to set the proxy_app, I've just tested [this doc](http://ethermint.readthedocs.io/en/develop/getting-started/getting-started.html#setup-ethermint) with latest master on both ethermint & tendermint
