### ISSUE TITLE
How to migrate ERC 20 token balances on Ethereum mainnet to Ethermint private network ?

### ISSUE THREAD

**Issue by sivachaitanya** [cosmos/ethermint-archive#378]
I had a successful token sale and I'm wondering what is the best possible to way to map the token balances on ERC-20 Ethereum mainnet to my private Ethermint address. How do you guys do it other than Oraclise? Please explain as elaborately as possible, Thanks

**Comment by ghost** [comment]
+1 waiting for this tutorial

**Comment by adrianbrink** [comment]
So, the best way is to wait for the peg zone that we are building at `github.com/cosmos/peggy` and use that to move the tokens.

**Comment by zramsay** [comment]
this'll come in https://github.com/cosmos/ethermint
