### ISSUE TITLE
Error while executing 'make install'

### ISSUE THREAD

**Issue by softlore** [cosmos/ethermint-archive#382]
I am using the following instructions to install ethermint.

```bash
go get -u -d github.com/tendermint/ethermint
go get -u -d github.com/tendermint/tendermint
cd $GOPATH/src/github.com/tendermint/ethermint

make install  //=> Error occurs when running make
```

**Missing Pacakages**

While executing make install, I got an error that the following packages were missing.
- github.com/ebuchman/fail-test
- github.com/ethereum/go-ethereum
- github.com/gorilla/websocket
- github.com/pkg/errors
- github.com/rcrowley/go-metrics
- github.com/tendermint/abci/client
- github.com/tendermint/abci/example/dummy
- github.com/tendermint/go-crypto
- github.com/tendermint/go-wire
- github.com/tendermint/go-wire/nowriter/tmlegacy
- github.com/tendermint/tmlibs/common
- github.com/tendermint/tmlibs/db
- github.com/tendermint/tmlibs/flowrate
- github.com/tendermint/tmlibs/log
- github.com/tendermint/tmlibs/merkle
- github.com/tendermint/tmlibs/pubsub
- github.com/tendermint/tmlibs/pubsub/query
- golang.org/x/crypto/nacl/box
- golang.org/x/crypto/nacl/secretbox
- golang.org/x/crypto/ripemd160
- github.com/mattn/go-colorable
- gopkg.in/urfave/cli.v1

I downloaded the above missing packages by running

```bash
go get -u package
```

**Error when running make install**

After downloading the missing packages, if I run ```make install```, I get the following message

```
CGO_ENABLED=1 go install -ldflags "-X github.com/tendermint/ethermint/version.GitCommit=`git rev-parse --short HEAD`" ./cmd/ethermint
# github.com/tendermint/ethermint/ethereum
ethereum/backend.go:54: too many arguments in call to eth.New
	have (*node.ServiceContext, *eth.Config, *EthState)
	want (*node.ServiceContext, *eth.Config)
ethereum/backend.go:67: cannot use NullBlockProcessor literal (type NullBlockProcessor) as type core.Validator in argument to ethereum.BlockChain().SetValidator:
	NullBlockProcessor does not implement core.Validator (wrong type for ValidateState method)
		have ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, *big.Int) error
		want ValidateState(*"github.com/ethereum/go-ethereum/core/types".Block, *"github.com/ethereum/go-ethereum/core/types".Block, *state.StateDB, "github.com/ethereum/go-ethereum/core/types".Receipts, uint64) error
ethereum/backend.go:95: undefined: "github.com/tendermint/abci/types".Result
ethereum/backend.go:120: cannot use tmHeader.Time (type int64) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
ethereum/backend.go:121: cannot use tmHeader.GetNumTxs() (type int32) as type uint64 in argument to b.es.UpdateHeaderWithTimeInfo
ethereum/eth_state.go:59: undefined: "github.com/tendermint/abci/types".Result
ethereum/eth_state.go:134: cannot convert *es.work.gp (type core.GasPool) to type big.Int
ethereum/eth_state.go:176: undefined: ethash.AccumulateRewards
ethereum/eth_state.go:177: cannot use ws.totalUsedGas (type *big.Int) as type uint64 in assignment
ethereum/eth_state.go:184: undefined: "github.com/tendermint/abci/types".Result
ethereum/eth_state.go:177: too many errors
make: *** [install] Error 2

```

**Comment by zramsay** [comment]
run `make get_vendor_deps` before `make install`. I'll update the documentation.

**Comment by zramsay** [comment]
try something like https://gist.github.com/zramsay/73f43a0800a461af3e74ccefd8004748

**Comment by zramsay** [comment]
see above commit
