### ISSUE TITLE
ethermint 0.5.4 - Cannot run ethermint executable, errors with panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by beichenh** [cosmos/ethermint-archive#388]
I followed the guide on https://github.com/tendermint/homebrew-tendermint to install Ethermint 0.5.4 through Homebrew on my iMac with MacOS High Sierra (10.13.3). My installation steps are as follows:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap tendermint/homebrew-tendermint
brew install tendermint
brew install ethermint

mkdir ~/.ethermint
vi ~/.ethermint/genesis.json
mkdir ~/.ethermint/keystore
vi ~/.ethermint/keystore/UTC--2016-10-21T22-30-03.071787745Z--7eff122b94897ea5b0e2a9abf47b86337fafebdc

ethermint --with-tendermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/cmd/utils.NewApp(0x49d2aaa, 0x5, 0x49f1700, 0x24, 0xc4203cebc8)
	/private/tmp/ethermint-20180218-31584-uh29tc/ethermint-0.5.4/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/cmd/utils/flags.go:98 +0x225

My environment variables are:
go version
go version go1.10 darwin/amd64

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/inschain-cto/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/inschain-cto/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cm/y30c2xx17yx3n98vtg3_hlkw0000gn/T/go-build142805572=/tmp/go-build -gno-record-gcc-switches -fno-common"

As you can see, my steps are pretty standard so I don't know what is wrong. Please help. Thanks in advance.

**Comment by emizzle** [comment]
How is this not an EXACT duplicate of the previous issue ([387](https://github.com/tendermint/ethermint/issues/388))?

**Comment by zramsay** [comment]
it is, thanks. closing in favour of #387

**Comment by beichenh** [comment]
The fix in #387 doesn't help with my case. /usr/local/Cellar/ethermint/0.5.4/bin/ethermint is the only compiled Ethermint library on my machine. 

I have:
/Users/inschain-cto/go/src/github.com/tendermint/ethermint/setup/
/usr/local/Cellar/go/1.10/
/usr/local/Cellar/ethermint/0.5.4/

However, the 0.5.3 binary downloaded from https://github.com/tendermint/ethermint/releases/download/v0.5.3/ethermint_0.5.3_darwin-10.6-amd64.zip does work. So there must be something wrong with the 0.5.4 build process. Please investigate. Thanks.

**Comment by nchennan** [comment]
I also have this problem .

xxxdeMacBook-Pro:~ xxx$ ethermint --datadir ~/.ethermint init
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/cmd/utils.NewApp(0x49d8a4a, 0x5, 0x49f76a0, 0x24, 0xc420239048)
	/Users/xxx/go/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/cmd/utils/flags.go:98 +0x225

**Comment by EnchanterIO** [comment]
This issue is happening because go-etherum utils `flags.go` expects a git commit but ethermint is passing a double, its version, 5.3.

They get by around this issue by on the fly replacing part of the code with a special gobuild flag:

```
BUILD_FLAGS = -ldflags "-X github.com/tendermint/ethermint/version.GitCommit=`git rev-parse --short HEAD`"
```

This magic (or hack imo.) is part of the Makefile build process. However you are building the binary, make sure a proper git commit is passed in.

If you don't want to use the Makefile and build it using GoLand IDE build process e.g, u can modify the `ethermint/cmd/ethermint/main.go` and temporarily hardcode  a valid git commit like so:

```
app = ethUtils.NewApp("a7e475f407bcd72da976522dd4121e1cefacd0bd", "the ethermint command line interface")
```

Then it will work.
