### ISSUE TITLE
Can't install from source

### ISSUE THREAD

**Issue by ghost** [cosmos/ethermint-archive#389]
## Description
*Following [documentation](http://ethermint.readthedocs.io/en/develop/getting-started/install.html#from-source)*
1. go get -u -d github.com/tendermint/ethermint
2. cd $GOPATH/src/github.com/tendermint/ethermint
3. go get github.com/Masterminds/glide
4. glide install
5. make install

Here on step 5 I got error:

```
> make install

CGO_ENABLED=1 go install -ldflags "-X github.com/tendermint/ethermint/version.GitCommit=`git rev-parse --short HEAD`" ./cmd/ethermint
# github.com/tendermint/ethermint/ethereum
ethereum/node.go:44: cannot use ctx (type *"github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli.v1".Context) as type *"github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1".Context in argument to utils.SetNodeConfig
ethereum/node.go:53: cannot use ctx (type *"github.com/tendermint/ethermint/vendor/gopkg.in/urfave/cli.v1".Context) as type *"github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1".Context in argument to utils.SetEthConfig
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 2
```

Tried with **golang** versions 1.6, 1.7, 1.8, 1.9, 1.10 - no success...

Could you please help to get it running?

**Comment by zramsay** [comment]
you can try the binaries here: https://github.com/tendermint/ethermint/releases/tag/v0.5.3

**Comment by adrianbrink** [comment]
@iredjee 

The steps to install Ethermint are:
```
go get github.com/tendermint/ethermint
cd $GOPAT/src/github.com/tendermint/ethermint
make get_vendor_deps
make install
```

Please let me know if that fixes your problem. Currently Ethermint should work with 1.8 and 1.9.

I'm closing this for now. If the above doesn't help you please ping me again in this issue.

**Comment by ghost** [comment]
Thank you guys for reply,

@adrianbrink tried `make get_vendor_deps` with golang:1.9. Helped to install without errors!

**Comment by adrianbrink** [comment]
Great to hear @iredjee 

What are you using Ethermint for?

**Comment by ghost** [comment]
@adrianbrink Cool that you ask about it :) The goal is to build own sidechain. I'm on research stage right now, looking on possible option how to do it on top of tendermint consensus, using ethermint is a big plus due to compatibility with ethereum tools, and I need some bridge between ethereum blockchain and own sidechain in the future.

Short recap
--
1. Get single tendermint/ethermint node up and running
2. Smart contract deployment and testing
3. Build sidechain - a cluster of nodes running ethermint (ideally with option to dynamically add new nodes)
4. Make somehow connection between ethereum network and own sidechain (custom business logic)

I'm not sure if all is possible at the moment with current solutions. So any help is appreciated. I'm currently struggling with step 1 :)
