### ISSUE TITLE
eth_getTransactionReceipt does not return status code

### ISSUE THREAD

**Issue by kaladinlight** [cosmos/ethermint-archive#394]
## Description
*tendermint version: 0.14.0-'88f5f21d'*
*ethermint version: 0.5.3-ea61396*

There is no status code returned from eth_getTransactionReceipt. This looks to be a pre Byzantium EVM implementation as there is only the root state returned along with showing cumulativeGasUsed to equal gas sent in sendTransaction for failing transaction. There should be an update to include the status code to check for transaction success/fail.

### Example Fail Output ###
{"jsonrpc":"2.0","id":209,"method":"eth_sendTransaction","params":[{"from":"0x49d2fc6e4736f75c01664eeb0dec84120022ae3e",**"gas":"0x47e7c4"**,"gasPrice":"0x174876e800","to":"0xe3e25072348e74b0f1a720060922b27e14c34a23","data":"0x2d580ef6000000000000000000000000a02035c8abd114909cb5020ca3dc5282aa9f05290000000000000000000000000000000000000000000000000000000000000000"}]}

"method":"eth_getTransactionReceipt","params ["0x85809fa72c5e97751e339b30bde1c71d03142381858acc9b77481e52a08ba48d"]}
{"jsonrpc":"2.0","id":212,"result": "blockHash":"0x74025ef30f36780e87cb5e2e07abc41cc1b6150004b9bb12b8e7f2304f58aff0","blockNumber":"0x68","contractAddress":null,**"cumulativeGasUsed":"0x47e7c4"**,"from":"0x49d2fc6e4736f75c01664eeb0dec84120022ae3e","gasUsed":"0x47e7c4","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",**"root":"0xe1976a05ba69ff4f29b71315c25c457261ed098cc321cb10ef71e3f73d06d492"**,"to":"0xe3e25072348e74b0f1a720060922b27e14c34a23","transactionHash":"0x85809fa72c5e97751e339b30bde1c71d03142381858acc9b77481e52a08ba48d","transactionIndex":"0x0"}}

**Comment by joeriexelmans** [comment]
It's because ethermint still uses go-ethereum 1.6.7-stable.

Status field was added in go-ethereum 1.7.

There's an issue about it here: #368

**Comment by zramsay** [comment]
yeah, this'll be handled in #368
