### ISSUE TITLE
how to  a new validator at a living net_work

### ISSUE THREAD

**Issue by lwgo2050** [cosmos/ethermint-archive#402]
i know there are two ways to become validator.

> - They can be pre-established in the genesis state
> - The ABCI app responds to the EndBlock message with changes to the existing validator set.
> but the first way main used for setting validator  before the net work started,the second way need to modify code to update validator at EndBlockMessage.
> 
and ethermint provide add a validator by sendTransaction,strategy code like this:
```
func (strategy *TxBasedValidatorsStrategy) CollectTx(tx *ethTypes.Transaction) {
	if reflect.DeepEqual(tx.To(), common.HexToAddress("0000000000000000000000000000000000000001")) {
		log.Info("Adding validator", "data", tx.Data())
		strategy.currentValidators = append(
			strategy.currentValidators,
			&types.Validator{
				PubKey: tx.Data(),
				Power:  tx.Value().Uint64(),
			},
		)
	}
}
```
I have add the strategy when create ethermint application,but when deliverTx,data become none ,
i think ethereum not support to send external account with data property,so i do not get pubkey,
any other method to add a Validator at a living network?

**Comment by lwgo2050** [comment]
@zramsay @adrianbrink

**Comment by zramsay** [comment]
this'll be fixed in https://github.com/cosmos/ethermint
