### ISSUE TITLE
Error on Tendermint node crash

### ISSUE THREAD

**Issue by dimitarjelev** [cosmos/ethermint-archive#403]
Not sure if this is not a duplicate of #315, but thank you in advance for the support.

**BUG REPORT :**

Tendermint version : v0.14.0
ethermint version : 0.5.3-deb7883
go-ethereum version: 1.6.7-stable

**Environment:**

OS : macOS High Sierra 10.13.3

**What happened:**

After tendermint crashes unexpectedly, connection between ethermint and tendermint is not established.

**Ethermint error**: 
```
ERROR[04-18|19:11:17]
########## BAD BLOCK #########
Chain config: {ChainID: 15 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Metropolis: <nil> Engine: unknown}

Number: 385
Hash: 0xd39397233fbf64a634f2ae8ce5dba1740c7e3a2c9ea0b0b3759393aa4bede6f3


Error: timestamp equals parent's
##############################

ERROR[04-18|19:11:17] Error getting latest ethereum state module=ethermint err="timestamp equals parent's"
```
**Tendermint error**:
```
E[04-18|16:11:17.509] Error in proxyAppConn.CommitSync             module=state err="Error code (1): Internal error;timestamp equals parent's"
E[04-18|16:11:17.509] Error on ApplyBlock. Did the application crash? Please restart tendermint module=consensus err="Commit failed for application: Error code (1): Internal error;timestamp equals parent's"
captured terminated, exiting...
```
After restarting the network, connection between Ethermint and Tendermint crashes.

**Tendermint error:** 
```
I[04-18|16:14:24.673] Executed block                               module=state height=385 validTxs=0 invalidTxs=0
E[04-18|16:14:24.674] Error in proxyAppConn.CommitSync             module=state err="Error code (1): Internal error;timestamp equals parent's"
ERROR: Failed to create node: Error starting proxy app connections: Error on replay: Commit failed for application: Error code (1): Internal error;timestamp equals parent's
```
**Ethermint error same as above.**

**What you expected to happen:**

Connection to be successfully established between Tendermint and Ethermint, and network to continue from its last state.

**How to reproduce:**

I was able to reproduce a few times by terminating the Tendermint process, while connection to Ethermint is established, but this is not happening every time.

**Comment by zramsay** [comment]
ethermint should not be considered stable at the moment; see #407

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint for latest ethermint
