### ISSUE TITLE
Make Install issue

### ISSUE THREAD

**Issue by berrehili** [cosmos/ethermint-archive#404]
Hi! 
I've been trying to install Ethermint with Tendermint for a moment now, I think I got to the final point but there is on unsolved issue on my side, and I can't get a grasp of it. All dependencies are installed but I still get after a "Make install" this error: 

```
CGO_ENABLED=1 go install -ldflags "-X github.com/tendermint/ethermint/version.GitCommit=`git rev-parse --short HEAD`" ./cmd/ethermint
github.com/tendermint/tendermint/types
../tendermint/types/event_bus.go:70:43: undefined: pubsub.NewTagMap
../tendermint/types/event_bus.go:117:39: undefined: pubsub.NewTagMap
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 2
```

I'm on Linux Ubuntu 16.04 with Golang 1.10

**Comment by zramsay** [comment]
see #407; there are a handful of issues needed to be resolved before. You might try using Tendermint 0.14.0 (see #401)

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint for the new work on ethermint
