### ISSUE TITLE
How to reward the node.

### ISSUE THREAD

**Issue by nchennan** [cosmos/ethermint-archive#406]
Test found that the node is rewarded to  0x0000000000000000000000000000000000000000，the node how to bind the account? How to reward to the node account? Hope to get your help, thank you.

**Comment by wadelee1986** [comment]
+1 

有没有测试 ethermint 的testnet， 我用两个节点 不行；

**Comment by wadelee1986** [comment]
我的微信:  15611084264

**Comment by nchennan** [comment]
[testnets-venus](http://ethermint.readthedocs.io/en/master/testnets/venus.html), The genesis.json for tendermint  validators ,  The config.toml for tendermint  seeds, The number is not the same.test fail.

**Comment by zramsay** [comment]
@nchennan the venus testnet instructions are out of date; these will be updated as part of #407

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
