### ISSUE TITLE
READ THIS FIRST (project update)

### ISSUE THREAD

**Issue by zramsay** [cosmos/ethermint-archive#407]
Hello and thank you for your interest in Ethermint! As you might have noticed from the (lack of) activity in this repository, the Ethermint project is currently not in active development by the Tendermint/Cosmos team. Currently, all efforts are focused on the [Cosmos SDK](https://github.com/cosmos/cosmos-sdk), which has yet-to-be-built features required by Ethermint. Once those features are available in the Cosmos SDK, Ethermint development will resume again.

NOTE: the project does not work out of the box and the documentation is out of date.

The following is a list of issues/PRs that need to be addressed before Ethermint can be considered stable:

- #367 
- #368 
- #369 
- #383 
- #386 
- #396 
- #400
- #401 
- #404 

We thank users for reporting bugs and submitting PRs; these will be addressed in due time. Anyone interested in full-time contributions may be interested in [applying as a developer for the Ethermint project](https://tendermint.com/careers/senior-software-engineer-ethermint).

**Comment by kidinamoto01** [comment]
@zramsay Totally, you should make this part of README (^-^)

**Comment by ebuchman** [comment]
Done, thanks guys

**Comment by wadelee1986** [comment]
Currently, all efforts are focused on the Cosmos SDK, which has yet-to-be-built features required by Ethermint. Once those features are available in the Cosmos SDK, Ethermint development will resume again.

1、what are the features you mentioned above ?


the project does not work out of the box 

2、 what do you refer by mentioning the "box" ?

**Comment by zramsay** [comment]
The specific feature set isn't super well-defined. Stay tuned.

"Out of the box" is a saying to mean something that works easily without a complicated series of steps. [see this link](https://en.wiktionary.org/wiki/out_of_the_box) for more info. There is no "box" per se

**Comment by zramsay** [comment]
@wadelee1986 you can track the ethermint integration milestone here: https://github.com/cosmos/cosmos-sdk/milestone/4

**Comment by EnchanterIO** [comment]
Hey @zramsay thx for your great work. Could u fix the milestone link please? I would like to watch the progress of Cosmos SDK to know when the focus will be shifted back to Ethermint as it's currenty unstable unfortunately.

**Comment by zramsay** [comment]
actually this issue is the best place to track progress.

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint for new ethermint
