### ISSUE TITLE
adding whisper to parameters

### ISSUE THREAD

**Issue by arsen3d** [cosmos/ethermint-archive#411]
Does anyone see a problem with enabling whisper with shh parameter? 
ethermint --with-tendermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin,shh

**Comment by zramsay** [comment]
this'll be addressed in https://github.com/cosmos/ethermint
