### ISSUE TITLE
Problem with allEvents in ethermint

### ISSUE THREAD

**Issue by filippetroviccc** [cosmos/ethermint-archive#412]
**Problem**
I am trying to list all Events, starting from block 0, emitted from my contract that has been deployed on ethermint. My code only receives  those events that happened after the watch function has been started. I tested script locally with ganache and everything works fine but on ethermint don't. I tried to log events with web3 and truffle-contract but the result is the same.

**Version**
_Ethermint_: Boris the Blade - v0.5.3
_OS_: Ubuntu 16.04

**Code**

```
const Web3 = require('web3');

const web3 = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:7545/'));
var MyContract = web3.eth.contract(contractJSON.abi);

const instance = MyContract.at(contractJSON.address);

const allEvents = instance.allEvents({
  from: 0,
  toBlock: 'latest'
});

allEvents.watch((err, res) => {
  if (err) {
    console.log(err);
  } else {
    console.log(res);
  }
});
```

What is the possible solution to this problem?

**Comment by zramsay** [comment]
please see #407. we will be in a position to help with your issue once ethermint is stable again

**Comment by alexanderbez** [comment]
Closing this for now. Once the 2.0 beta is released under https://github.com/cosmos/ethermint, we can follow up from there if the issue persists 👍.

**Comment by zramsay** [comment]
see https://github.com/cosmos/ethermint for a new ethermint
