### ISSUE TITLE
How to implement a reward strategy based on gas used

### ISSUE THREAD

**Issue by EnchanterIO** [cosmos/ethermint-archive#414]
## Reverse engineering

According to `app.go EthermintApplication` a reward strategy can be configured:

```go
type Strategy struct {
	MinerRewardStrategy
	ValidatorsStrategy
}
```

By default there is no strategy and an empty Receiver is configured:

```go
func (app *EthermintApplication) Receiver() common.Address {
	if app.strategy != nil {
		return app.strategy.Receiver()
	}
	return common.Address{}
}
```

I created a new account to test what will happen if I actually specify a receiver so I hardcoded one and apparently I receive 5ETH on each **commit**.

Where is this 5ETH coming from? Let's see. It's not substracted from the main acc, neither it's the gas price * gas used of a transaction as that's like 0.00...xy ETH.

Following the code on how is the **Receiver** used I endup in a struct called **WorkState** which seems to be some kind of stateful processor for each block.

Long story short seems like the Receiver is added as a `tx.header.coinbase` account to each **Block**.

Now the magical part. So how is possible I receive 5ETH on each block?

According to `app.go`:

```go
func (app *EthermintApplication) EndBlock(height uint64) abciTypes.ResponseEndBlock {
	app.logger.Debug("EndBlock", "height", height) // nolint: errcheck
	app.backend.AccumulateRewards(app.strategy)
	return app.GetUpdatedValidators()
}
```

Each time a Block is commited, **EthState**'s attribute (before mentioned) **workState** is called to accomulate rewards to the miner in the following way:

```go
state.AddBalance(header.Coinbase, reward)
```

where **reward** is a hardcoded, ladies and gentlmen, `big.NewInt(5e+18)` 5ETH!

So, that solves the mystery where our ETH comes from. If I am correct, the **coinbase account in state is artifically increased by 5ETH out of the blue on each successful block?**
 
## Question: What about validators?

Each transaction costs the **Sender** XY amount of gas. **This gas is substracted from the Sender but where does it go?**

How can I find out the balance of my validator? Because by default it seems like my Validator is not receiving any ETH. I opened priv_validator.json, converted the string address to hex, attached web3, run `eth.getBalance("0x3431423137454433313945464436333639323843")` which resulted in `0`.

Is there some documentation how or, what would be the best way to implement a strategy rewarding validators and assigning them the lost gas?

@zramsay @melekes

**Comment by zramsay** [comment]
this will change and eventually be documented in the new version of ethermint: https://github.com/cosmos/ethermint
