### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/ethermint-archive#418]
Excellent Discussion from: https://github.com/cosmos/ethermint_bak/issues/9

**Comment by alexanderbez** [comment]
@jackzampolin this is ready to be done now. We should at the minimum run `make test-unit` and `make test-lint` 👍 . CLI tests will come later. #453 will need to be merged first.

**Comment by jackzampolin** [comment]
I'll get with @greg-szabo to get this hooked up in circle.
