### ISSUE TITLE
the problem about install ethermint from source

### ISSUE THREAD

**Issue by zyc-happy** [cosmos/ethermint-archive#428]
1 OS
Linux version 3.10.0-693.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Sep 12 22:26:13 UTC 2017
2 go
go version go1.9.2 linux/amd64
3 tendermint version
0.22.0-64bae01d

4 followed 
http://ethermint.readthedocs.io/en/develop/getting-started/install.html
![image](https://user-images.githubusercontent.com/2224215/42741578-2de1c928-88e6-11e8-9cb6-049943222540.png)

and then:
![12](https://user-images.githubusercontent.com/2224215/42741590-4535c2b4-88e6-11e8-91a8-8bd36a7c1f57.png)

5 my tendermint is OK, so WHAT happened？

**Comment by alexanderbez** [comment]
@zyc-happy Sorry for the confusion. That documentation is deprecated and references version 1 of the Ethermint implementation which can be found [here](https://github.com/cosmos/ethermint_bak). 

You're running the deprecated Ethermint install instructions with version 2. Version 2 is in highly active development and in it's early stages. You are more than welcome to follow documentation in the README there if you'd like.

**Comment by alexanderbez** [comment]
Will close this for now.
