### ISSUE TITLE
Build/Install Ethermint

### ISSUE THREAD

**Issue by ricardojmf** [cosmos/ethermint-archive#43]
Hello,

I'm having troubles with ethermint installation/build, i have this error:

![image](https://cloud.githubusercontent.com/assets/4780289/23550677/350b0806-000a-11e7-8f73-9050b1d2047d.png)

I'm using windows 8.1, go 1.8 and glide 0.12.3

**Comment by adrianbrink** [comment]
Ubuntu 16.04

Same error even though I have to ```cd``` into cmd/ethermint and then run ```go install```.
![screenshot from 2017-03-22 20-36-05](https://cloud.githubusercontent.com/assets/11320251/24217159/331f0f62-0f3f-11e7-83a9-3e7445ae60ff.png)

**Comment by ricardojmf** [comment]
Sorry I forgot to close this issue, I already solved it, it had to be with the workspace that was using.

In order to install ethermint correctly you have to follow this steps:

1º Setup go workspace correctly
2ª go get github.com/tendermint/ethermint
3ª cd [GO WORKSPACE PATH]/src/github.com/tendermint/ethermint/cmd/ethermint
4ª go install

That should solve the problem :)

**Comment by adrianbrink** [comment]
Alright, I figured out the issue. Running ```glide install``` will update dependencies which are then incompatible and throw the error above.

If you don't run ```glide install``` then it will work fine. :-)

**Comment by adrianbrink** [comment]
#48 used for tracking the issue with running ```glide install```
