### ISSUE TITLE
Implement ABCI Interface

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/ethermint-archive#436]
Building upon the existing Ethermint application, implement the initial ABCI interface along side any necessary keepers and mappers.

**Comment by alexanderbez** [comment]
Note from #451, implement unit tests for ante handlers.

**Comment by AdityaSripal** [comment]
Will work on ante-handler tests

**Comment by jackzampolin** [comment]
Should we break this up into a couple of issues?

**Comment by AdityaSripal** [comment]
The only thing i can imagine being a seperate issue is implementing the handler for regular Ethereum transactions. Everything else should be trivial

**Comment by jackzampolin** [comment]
I think that might help to break up the PR a bit too. I've gone ahead and done that. Thanks @AdityaSripal

**Comment by alexanderbez** [comment]
@AdityaSripal I assigned #462 to you :-)

I'll update this issue with what I think actually needs to be done.
