### ISSUE TITLE
Include hard-spoon generated database files in gitignore

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ethermint-archive#441]
__Proposal:__ Add `code.db/`, `state.db/`, and `structlogs.txt` to gitignore

__Current behavior:__ Currently can accidentally add and commit these files

__Desired behavior:__ `git add .` on ethermint/ will not add the above files and directories

__Use case:__ Convenience

Requests may be closed if we're not actively planning to work on them.

**Comment by alexanderbez** [comment]
@AdityaSripal I suggested to @jackzampolin that he add these to his local global gitignore. I dont think we should pollute the repo's gitignore with these as they most likely will not exist for long.
