### ISSUE TITLE
Enable state reconstructing using references

### ISSUE THREAD

**Issue by eugenefine** [cosmos/ethermint-archive#46]
adamscislowicz [4:12 PM] :

In this case the idea is that for a given contract address, you would use an unfilled reference. Next time a block effects the state of that contract address (a namespace) it would fill the reference with that block ID. So at block 1, addr B sets up am unfilled reference (it will point to NULL). At block 30 B is updated and so the unfilled reference block 1 points to is then updated to block 30. So now a node trying to construct the state of B through time can skip from block 1 to block

**Comment by adrianbrink** [comment]
We are not locking to implement extra logic on top of go-ethereum and hence I will close this issue.
