### ISSUE TITLE
Implement Handler for Ethereum transactions

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/ethermint-archive#462]
This is a piece of #436 that should be separate as it will require more work to complete. See that issue for more details.

**Comment by alexanderbez** [comment]
@jackzampolin we already have the ante handler implemented (most of it) to handle routing. I guess what we need here to actually pass the tx to the EVM.

**Comment by vaibhavchellani** [comment]
this can be closed i think @jackzampolin

**Comment by jackzampolin** [comment]
Thank you for catching this @vaibhavchellani 🙈
