### ISSUE TITLE
Start Documentation

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/ethermint-archive#468]
We've been making some important architectural decisions that will impact the future engineering design and the overall direction of Ethermint. It's vital we start documenting these now so we can look back and know why we made the decisions we've made. In addition, as the project grows larger, this will be even more pivotal.

/cc @jackzampolin @AdityaSripal

**Comment by jackzampolin** [comment]
Yup! I think we maybe need the following files:

```
- RPC - /docs/rpc.md
- SDK App - /docs/app.md
- Arch/low level concerns - /docs/arch.md
```
Thoughts?

cc @AdityaSripal @AlexeyAkhunov

**Comment by alexanderbez** [comment]
Something along those lines...for now just the major things. Prob `docs/intro` and `docs/spec/transactions`
