### ISSUE TITLE
Running "glide install" causes a build error

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#48]
Running ```glide install``` causes some dependencies to be updated which when running ```go install ./cmd/ethermint``` causes a build error. 

![screenshot from 2017-03-22 20-36-05](https://cloud.githubusercontent.com/assets/11320251/24217798/59ebc5de-0f41-11e7-8f27-639bdce9e57d.png)

**Comment by ramilexe** [comment]
@adrianbrink look at https://github.com/tendermint/ethermint/issues/27#issuecomment-280848866
