### ISSUE TITLE
ethermint command not found

### ISSUE THREAD

**Issue by xuyongchaovv** [cosmos/ethermint-archive#484]
i Check out previous documents,old path is https://github.com/tendermint/ethermint.git ,why this path is redirect to https://github.com/cosmos/ethermint.git,and i can not find ethermint command

**Comment by alexanderbez** [comment]
@HarderThenBetter we ported the old `tendermint/ethermint` to [cosmos/ethermint_bak](https://github.com/cosmos/ethermint_bak). Now, `cosmos/ethermint` is the existing place for the next iteration of Ethermint which is complete redesign. There are no working binaries yet as it is still a big WIP.

Development is coming along nicely though, so stay tuned. If your project depend on the old prototype implementation, they can be found in the link I posted above 👍
