### ISSUE TITLE
Ethermint readthedocs link is broken

### ISSUE THREAD

**Issue by ghost** [cosmos/ethermint-archive#497]
__Proposal:__ [Description of the feature]
Re-enable ethermint readthedocs link
https://readthedocs.org/projects/ethermint/?fromdocs=ethermint

__Current behavior:__ [What currently happens]
Below document is broken
https://readthedocs.org/projects/ethermint/?fromdocs=ethermint

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by alexanderbez** [comment]
@zramsay do we currently support readthedocs in the SDK. That was updated in favor of what?

**Comment by zramsay** [comment]
we moved to using vuepress and could implement here. AFAICT, there's no link to ReadTheDocs from this repo (if there is, i'll remove)

**Comment by jacohend** [comment]
Could you please link to the new documentation?

**Comment by zramsay** [comment]
@jacohend the README of this repo is it

**Comment by ghost** [comment]
sorry I wasn't clear about my question. I googled and found readthedocs link. 

so where is the most up-to-date documentation for ethermint to follow and use this repo?

**Comment by ghost** [comment]
> @jacohend the README of this repo is it

But how do you start `ethermint` chain along with tendermint etc? there is only test.

and how do you interact with `ethermint`? the README.md is missing a lot of details

**Comment by zramsay** [comment]
> But how do you start ethermint chain along with tendermint etc? there is only test. and how do you interact with ethermint?  

You don't (sorry to be blunt). Ethermint is pre-alpha, as noted in the warning at the top of the README. Also note that the first line of the `What is it?` section says: `ethermint` **will be** ... so hang tight and see [this comment](https://github.com/cosmos/ethermint/issues/479#issuecomment-439985581)
