### ISSUE TITLE
running `emintd` `emintcli` do nothing 

### ISSUE THREAD

**Issue by jakeonchain** [cosmos/ethermint-archive#500]
__System info:__ Current master, Mac OS 10.13.6

__Steps to reproduce:__

run 

```
emintd
emintcli
```

__Expected behavior:__start the ethermint node

__Actual behavior:__ nothing happends

__Additional info:__ No outputs etc.

How can I start an ethermint node? Thanks.

**Comment by alexanderbez** [comment]
@jakeonchain see my previous comment in #479. We will have binaries that you may execute soon! 😄
