### ISSUE TITLE
Dockerfile no such file or directory

### ISSUE THREAD

**Issue by jacohend** [cosmos/ethermint-archive#502]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

Linux mate-MACH-WX9 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

__Steps to reproduce:__

1. docker build -t ethermint . --no-cache
2. Received 
```
Step 10/18 : COPY --from=build-env /go/src/github.com/cosmos/ethermint/build/ethermint /usr/bin/ethermint
COPY failed: stat /var/lib/docker/overlay2/47ff6aac86b0205bf623bcf072448f2525bd05b5135c3ba06e214ff0f3d8b1ce/merged/go/src/github.com/cosmos/ethermint/build/ethermint: no such file or directory
```

__Expected behavior:__ ethermint to be copied to `/usr/bin/ethermint` in Docker image

__Actual behavior:__ Ethermint has been renamed to build/emintd and build/emintcli, so the copy command in the dockerfile will always fail.

**Comment by alexanderbez** [comment]
Good catch @jacohend! Thanks for submitting the issue. @jackzampolin do you mind taking a look at this?
