### ISSUE TITLE
web3 & contracts usage

### ISSUE THREAD

**Issue by konstantinzolotarev** [cosmos/ethermint-archive#51]
I'm trying to deploy new contract to `ethermint` using `web3.js` library. 

And faced with this issues:
1. last docker image of `tendermint/ethermint` is working but does not allow me to unlock account.

Code:
```javascript
web3.personal.unlockAccount(account, '1234', (err) => {})
```
Returns: 
```
Could not unlock account:  Error: The method personal_unlockAccount does not exist/is not available
```

Without unlock Im getting message:
```
Error: authentication needed: password or unlock
```

**Comment by illya13** [comment]
`personal` API is not enabled by default, start `ethermint` smth like 
```
--rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcapi "db,eth,web3,personal,admin,txpool"
```

**Comment by konstantinzolotarev** [comment]
Shouldn't it be in default docker image ? 
Otherwise it's useless because you couldn't use almost anything from ethermint.

**Comment by adrianbrink** [comment]
@konstantinzolotarev The goal is to be as similar as go-ethereum in its behaviour. I don't know whether it is enabled by default in their client though.

**Comment by illya13** [comment]
https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options
```--rpcapi value         API's offered over the HTTP-RPC interface (default: "eth,net,web3")```

**Comment by illya13** [comment]
... and you can pass this as additional params to a docker image as well

**Comment by ebuchman** [comment]
An update has been pushed. The docker container defaults to starting with `--rpcapi "eth,net,web3,personal,admin"`
