### ISSUE TITLE
ethermint fails with "Killed: 9"

### ISSUE THREAD

**Issue by davebryson** [cosmos/ethermint-archive#53]
OSX 10.12.4
go1.8 darwin/amd64

Installed ethermint via `go get`  and built both ethermint and tendermint.

`TMROOT=~/.ethermint tendermint init` works fine
`ethermint -datadir ~/.ethermint init dev/genesis.json` fails with `Killed: 9`

Any idea what may be causing this?

**Comment by melekes** [comment]
`Killed: 9` means the process was killed by the OS. See `/var/log/system.log` for a reason.

**Comment by davebryson** [comment]
No output in `system.log` for this.

**Comment by davebryson** [comment]
Actually the issue seems to be with the latest Xcode tools on OS X: 10.12.4 :  [golang/issues](https://github.com/golang/go/issues/19734).  This is a work around that worked for me:

`go build -ldflags -s ./cmd/ethermint` 

Note using `build` not `install` with the additional flags.

**Comment by melekes** [comment]
Ok, thanks!

Closing it since it is a go issue.
