### ISSUE TITLE
Remove the hardcoded url for RPC node

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#55]
Currently, in ```backend.go``` we hardcode "localhost" as the url for the RPC node that ethermint talks to. This is not ideal if we want to keep the ABCI app and tendermint core modular, so ideally we want to add another flag to provide that url value.

Specifically, I am running into that issue when dockerizing a multi-node setup, since I am running 4 instances of tendermint that each talk to their own instance of the ABCI app (which is another 4 containers in total).

**Comment by ramilexe** [comment]
@adrianbrink do you mean this line https://github.com/tendermint/ethermint/blob/master/ethereum/node.go#L69 ?

> Specifically, I am running into that issue when dockerizing a multi-node setup, since I am running 4 instances of tendermint that each talk to their own instance of the ABCI app (which is another 4 containers in total).

How do you split tendermint and ABCI app in ethermint?

**Comment by adrianbrink** [comment]
Yes :-)

So I think it is best to run a tendermint core node and an ABCI node separately and only allow them to communicate over RPC. This makes it much easier to setup dockerized solutions. For example, it would allow you to have multiple ABCI frontends on a single core node in order to hold the load.

**Comment by AFDudley** [comment]
I'm confused. Why would you have one tendermint core support 4 instances of the same ABCI app?

**Comment by adrianbrink** [comment]
@AFDudley Good point. I thought of it the wrong way around. It makes little sense.

**Comment by adrianbrink** [comment]
I am closing this in favour of #63.

**Comment by ramilexe** [comment]
PR https://github.com/tendermint/ethermint/pull/70
