### ISSUE TITLE
Ethermint does not return 'over gas limit' error

### ISSUE THREAD

**Issue by ricardojmf** [cosmos/ethermint-archive#58]
- Ethermint not giving the over gas limit error.
- No error is displayed;
- The first transaction passes, but with data bugs;
- Future requests to the node have no answer and remain listening for an anwser for ever, freezing future transactions.

Only solved by restarting nodes.

**Comment by ramilexe** [comment]
Hi @ricardojmf 
Could you provide test case (params for ethermint and web3 js code)?

**Comment by adrianbrink** [comment]
The check should be done in validateTx() in app/app.go

**Comment by adrianbrink** [comment]
From what I understand this has been closed by implementing the check whether the current transaction's gas usage would exceed the remaining gas in the gaspool.
