### ISSUE TITLE
Use local ABCI app instead of running a server

### ISSUE THREAD

**Issue by ebuchman** [cosmos/ethermint-archive#63]

**Comment by ramilexe** [comment]
[Remove the hardcoded url for RPC node](https://github.com/tendermint/ethermint/issues/55)

**Comment by adrianbrink** [comment]
```Ethermint``` has to connect to ```tendermint core``` over RPC. Currently the connection URL is hard-coded [here](https://github.com/tendermint/ethermint/blob/master/ethereum/node.go#L69).

**Comment by ramilexe** [comment]
https://github.com/tendermint/ethermint/pull/70

**Comment by ramilexe** [comment]
Can we close it due PR (https://github.com/tendermint/ethermint/pull/70) is merged?
