### ISSUE TITLE
Master & Develop broken due to changes in PrivValidator

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#67]
I just tried to run the newest develop and master branches of ethermint, however it errors out saying that it can't unmarshal the priv_validator.json.

```
➜  ethermint git:(master) TMROOT=~/.ethermint tendermint init

NOTE[04-27|13:51:57] Initialized tendermint                   module=main genesis=/Users/adrian/.ethermint/genesis.json priv_validator=/Users/adrian/.ethermint/priv_validator.json
➜  ethermint git:(master) ethermint -datadir ~/.ethermint init dev/genesis.json

➜  ethermint git:(master) cp -r dev/keystore ~/.ethermint/keystore

➜  ethermint git:(master) ethermint --datadir ~/.ethermint
tm node
NOTE[04-27|13:52:13] Waiting for new connection...            module=abci-server
Error reading PrivValidator from /Users/adrian/.ethermint/priv_validator.json: Expected type [Byte,?] but got type map[string]interface {}
```

Since, this is happening in the tendermint core code, could it have something to do with the way go handles dependencies? 

I just tested tendermint with the dummy app and here tendermint can read the privKey.

@ebuchman Could this be connected to the merging of the repos? And also, what is the correct format for a privKey?

**Comment by ramilexe** [comment]
Can not reproduce.
Please provide:

- `tendermint version`
- `ethermint version`
- `cat /Users/adrian/.ethermint/priv_validator.json`

**Comment by ebuchman** [comment]
You need to use tendermint master with ethermint. I suspect you are using develop
