### ISSUE TITLE
Remove PendingBlock and replace it with Pending

### ISSUE THREAD

**Issue by ebuchman** [cosmos/ethermint-archive#71]
use `block, _ := pending.Pending()` for things that dont need state

Will need to add a commit to tendermint/go-ethereum too

**Comment by ramilexe** [comment]
Please merge PR in go-ethereum repository https://github.com/tendermint/go-ethereum/pull/1
Then I'll change commit hash in glide.lock

**Comment by ramilexe** [comment]
This issue blocked by this https://github.com/tendermint/go-ethereum/pull/1 PR
