### ISSUE TITLE
Allocate work slices from BeginBlock

### ISSUE THREAD

**Issue by ebuchman** [cosmos/ethermint-archive#72]
avoid append for the txs, receipts. logs I dont think we can do anything about tho

**Comment by adrianbrink** [comment]
@ebuchman Could you elaborate on what you mean by this?

**Comment by ebuchman** [comment]
https://github.com/tendermint/ethermint/blob/master/ethereum/backend.go#L264
we could use `make` in BeginBlock instead since the tendermint header includes NumTxs
