### ISSUE TITLE
Unlock/Password Flag doesn't work

### ISSUE THREAD

**Issue by nodech** [cosmos/ethermint-archive#80]
Ethermint version: `0.1.0-unstable-b5127d3f Ethereum/1.5.9-stable`

I want to unlock some accounts on start:
`ethermint --datadir /tmp/nnetwork --rpc --rpcapi eth,net,web3,personal,admin --unlock 9e8b5ba8a61edc2e48da13d7bdd712d31e13901e --password ./passwords`

This doesn't unlock accounts.

**Comment by adrianbrink** [comment]
@nodar-chkuaselidze Could you provide some logs of the error messages that you got, if any.

**Comment by nodech** [comment]
There was none, but Something like this was expected:
```
I0508 14:48:21.542556 cmd/geth/accountcmd.go:206] Unlocked account 77e0d0f7b13e4b322c08f6e5b74ea1ef5844102a

I0508 14:48:22.498255 cmd/geth/accountcmd.go:206] Unlocked account 85418fff140231f43e7028af2588fa3e5b614c4d
```

**Comment by adrianbrink** [comment]
@ebuchman I'll push this into the next release, as it is not as straight forward as I thought.

**Comment by ramilexe** [comment]
Looks like fixed in commit https://github.com/tendermint/ethermint/commit/3f6f8806ea85f8467c1a0261e877754f44513763

**Comment by adrianbrink** [comment]
@nodar-chkuaselidze Can you check that all the edge cases work
