### ISSUE TITLE
Add tendermint init to ethermint

### ISSUE THREAD

**Issue by ramilexe** [cosmos/ethermint-archive#83]
To create new fresh instance of ethermint you need to run:

```
TMROOT=/tmp/a1 tendermint init
ethermint -datadir /tmp/a1 init dev/genesis.json
cp -r dev/keystore /tmp/a1/keystore
ethermint --datadir /tmp/a1
```

I suggest to implement `tendermint init` inside ethermint.
Maybe `ethermint init-tendermint`? :confused:

**Comment by adrianbrink** [comment]
The goal will be to run ethermint and tendermint not in-process but rather out-of-process.

**Comment by ramilexe** [comment]
The problem is you need `tendermint` binary to create `ethermint` fresh instance. Why?

**Comment by adrianbrink** [comment]
Mh, that's true. Let's work on removing that dependency then :-)
