### ISSUE TITLE
Build binaries for each release tag

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#89]

**Comment by ramilexe** [comment]
Do you want build it with CI?

**Comment by adrianbrink** [comment]
Yes

**Comment by ramilexe** [comment]
* define artifacts in circle.yaml (https://circleci.com/docs/1.0/configuration/#artifacts)
* should we build only for x64 platform or add another?

**Comment by ramilexe** [comment]
Also, should we build docker image? Does CirlceCI have installed docker for it?

**Comment by adrianbrink** [comment]
For now we will manually build them once every release with build scripts. I think it is a good idea to build binary releases and docker images. Once we are adding more devops capacity, we might get someone to automatically build releases and docker images using CircleCI.

So the goal is to have a bash script that allows us to manually build binary release tags and docker images. This can be a base version: https://github.com/tendermint/tendermint/tree/master/scripts
