### ISSUE TITLE
Enable stateful CheckTx

### ISSUE THREAD

**Issue by ebuchman** [cosmos/ethermint-archive#9]
See https://github.com/tendermint/ethermint/pull/4

**Comment by adrianbrink** [comment]
1. Change AppendTx to call ApplyTransaction and return the correct information. This will support usage where nonces increment quickly, e.g. multiple txs per block from the same address.
2. In the future, make CheckTx better by mirroring logic in promoteExecutables() to work for each tx. And also create a new ManagedState upon ABCI Commit(). This will make CheckTx return correct results in the mempool.
3. Make CheckTx also return address & nonce information and allow tendermint to handle promoting txs that have become valid.

Copied the remaining points from #4.

**Comment by zramsay** [comment]
#276
