### ISSUE TITLE
Remove ethermint's dependency on tendermint for initialising a fresh instance

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#95]

**Comment by ramilexe** [comment]
@adrianbrink does `ethermint init-tendermint` command ok for you?

**Comment by adrianbrink** [comment]
It should just be ```ethermint init``` and only initialise the things relevant to the ABCI app. It shouldn't touch any of the tendermint core node. Let's just split tendermint core and ethermint completely, as to get a clearer separation of concerns.
